### ISSUE TITLE
Starting RTB

### ISSUE THREAD

**Issue by sfulol** [moloch--/RootTheBox#102]
Hi. I got errors when starting the script/server. Any ideas?

./rootthebox.py --start
[I 150826 04:20:26 GameHistory:53] Loading game history from database ...
[I 150826 04:20:26 GameHistory:64] Cached snapshot (1 of 1)
Traceback (most recent call last):
  File "./rootthebox.py", line 455, in <module>
    start()
  File "./rootthebox.py", line 43, in start
    from handlers import start_server
  File "/root/rtb/RootTheBox/handlers/__init__.py", line 50, in <module>
    from handlers.ScoreboardHandlers import *
  File "/root/rtb/RootTheBox/handlers/ScoreboardHandlers.py", line 120, in <module>
    class ScoreboardHistorySocketHandler(WebSocketHandler):
  File "/root/rtb/RootTheBox/handlers/ScoreboardHandlers.py", line 123, in ScoreboardHistorySocketHandler
    game_history = GameHistory.instance()
  File "/root/rtb/RootTheBox/libs/Singleton.py", line 40, in instance
    self._instance = self._decorated()
  File "/root/rtb/RootTheBox/libs/GameHistory.py", line 48, in __init__
    self._load()
  File "/root/rtb/RootTheBox/libs/GameHistory.py", line 66, in _load
    self.cache.set(snapshot.key, snapshot.to_dict())
  File "/root/rtb/RootTheBox/models/Snapshot.py", line 71, in to_dict
    return {'timestamp': unix_time.total_seconds(), 'scoreboard': data}
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'

**Comment by moloch--** [comment]
What is your `--version` information?

**Comment by sfulol** [comment]
./rootthebox.py --version
Root the Box v0.6.1
 SQL Alchemy v1.0.8
     Torando v4.2.1

**Comment by sfulol** [comment]
Nevermind, error on my part running on an old distro I had laying around. Changed to a latest linux distro and it works! Thanks!

**Comment by moloch--** [comment]
Okay, good to know, I was almost out of ideas, I typically only see this type of error on older versions of SQLAlchemy.
