### ISSUE TITLE
Exception: Cannot redirect after headers have been written

### ISSUE THREAD

**Issue by roland56270** [moloch--/RootTheBox#111]
Hello,

Since few days, I try to implement a timer to start and stop the game automatically. All my code works pretty well but y have just an error while I redirect the user after the timer has finished (self.redirect('/user')) . 

My error : 
Exception in thread Timer:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/root/RootThebox/handlers/AdminHandlers/AdminGameHandlers.py", line 96, in start_timer
    self.redirect('/user')
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 664, in redirect
    raise Exception("Cannot redirect after headers have been written")
Exception: Cannot redirect after headers have been written

And the modified start_game function : 

    def start_game(self):
        ''' Start the game and any related callbacks '''
        if not self.application.settings['game_started']:
            logging.info("The game is about to begin, good hunting!")
	    timer_hours = abs(int(self.get_argument('how-long-hours', '2')))
	    timer_minutes = abs(int(self.get_argument('how-long-minutes', '0')))
	    timer_starting_time_tmp = datetime.datetime.now()
	    timer_starting_time = timer_starting_time_tmp.strftime('%Y/%m/%d %H:%M:%S')
	    timeout = timer_hours*60+timer_minutes
	    timer_ending_time = (timer_starting_time_tmp + datetime.timedelta(minutes=timeout)).strftime('%Y/%m/%d %H:%M:%S')
	    self.application.settings['timer_starting_time'] = timer_starting_time
	    self.application.settings['timer_ending_time'] = timer_ending_time
	    self.application.settings['game_started'] = True
            self.application.settings['history_callback'].start()
            if self.config.use_bots:
                self.application.settings['score_bots_callback'].start()
            self.set_all_users_lock(False)
	    if self.application.settings['timer_enable'] == True:
		''' I set 7sec instead of timeout variable for the test '''
		self.t1 = threading.Timer(7, self.start_timer)
		self.t1.setName('Timer')
		self.t1.start()

    def start_timer(self):
	self.stop_game()
	self.t1.cancel()
        self.redirect('/user')

Do you have any idea of the solution ?

Thank you in advance for you answer.

**Comment by moloch--** [comment]
Have you modified [`self.post()`](https://github.com/moloch--/RootTheBox/blob/master/handlers/AdminHandlers/AdminGameHandlers.py#L57)? If not you may be calling `self.redirect('/user')` twice; once in `start_timer` and again once again when `start_game()` returns, this will cause an exception like the one above since you're redirecting after redirecting (I'm sorta guessing here but that's what it looks like to me).

On a side note, you may want to avoid using standard Python threads for this, as [Tornado](http://www.tornadoweb.org/en/stable/) is an asynchronous framework. Asynchronous programming and threading are both forms of concurrent programming (but at the same time very different), mixing them tends to get very complicated and cause all sorts of problems.

Torando's [PeriodicCallback](http://www.tornadoweb.org/en/stable/ioloop.html?highlight=periodic%20callback#tornado.ioloop.PeriodicCallback) may suite your needs, otherwise look into [`tornado.concurrent`](http://www.tornadoweb.org/en/stable/concurrent.html?highlight=thread) for threading support

**Comment by roland56270** [comment]
Okay, I understood the problem.

I have removed start_timer function and replace it with a javascript call of start_game and stop_game. It seem to work but I will do some additional tests in order to validate this feature.

Thanks a lot for your help :)
