### ISSUE TITLE
Federal Reserve Bank console errors

### ISSUE THREAD

**Issue by F13** [moloch--/RootTheBox#145]
This issue contains three errors I found in the Federal Reserve Bank console. I'm happy to submit the changes myself if there is no opinion / additional input on my comments.

---
The `checkArity` parameter in the JQuery Terminal Emulator is 1. not properly used, and 2. unnecessary (since the RtB code already checks against `undefined`). Because it's not checked against (and even if it were it defaults to `true`), when a user inputs the command `intro` with no parameters they get an error from the Terminal Emulator library rather than RtB code (which is much more helpful).

Given error:
```
[Arity] wrong number of arguments. Function 'intro' expect 1 got 0
```
Better RtB error:
```
-!- ERROR: Not a valid option; 'off', 'ascii', or 'metasploit'
```

An update from JQuery Terminal Emulator 0.7.12 to something newer (1.7.2 is the current version) may fix the issue. Alternatively, the fix is simple if an update is not desired/necessary. The following changes should be made to `terminal.min.js`:

1. Set `checkArity` in `d.terminal.defaults` to `false`
2. Modify an `if` check in function `o`, immediately after `if(w==="function")`, from `if(h&&r.length!==j.args.length)` to `if(h&&m.checkArity&&r.length!==j.args.length)`

---
Another error in JQuery Terminal Emulator. An input of `?` will cause a syntax error in the regex:
```
root@mainframe:~# ?
[USER]: Invalid regular expression: /^? /: Nothing to repeat
SyntaxError: Invalid regular expression: /^? /: Nothing to repeat
    at new RegExp (native)
    at RegExp (native)
    at ka (http://localhost:8888/static/js/libs/terminal.min.js:32:144)
    at Object.d.terminal.parseCommand (http://localhost:8888/static/js/libs/terminal.min.js:77:249)
    at i (http://localhost:8888/static/js/libs/terminal.min.js:87:371)
    at Object.interpreter (http://localhost:8888/static/js/libs/terminal.min.js:89:105)
    at Object.H [as commands] (http://localhost:8888/static/js/libs/terminal.min.js:97:173)
    at HTMLHtmlElement.x (http://localhost:8888/static/js/libs/terminal.min.js:42:175)
    at HTMLHtmlElement.x.event.dispatch (http://localhost:8888/static/js/jquery.min.js:4:10006)
    at HTMLHtmlElement.y.handle (http://localhost:8888/static/js/jquery.min.js:4:6789)
```
This is because the `escape_regex` function doesn't include the `?` character. Once again, an update may fix the issue. Otherwise, the character just needs to be added to the list
```js
escape_regex:function(c){return c.replace(/([\^\$\[\]\(\)\+\*\.\|])/g,"\\$1")}
```
like such:
```js
escape_regex:function(c){return c.replace(/([\^\$\?\[\]\(\)\+\*\.\|])/g,"\\$1")}
```
Straightforward, unless an update to JQuery Terminal Emulator is desired.

---
The `intro` function doesn't properly handle a numeric value provided as the first parameter.
```
root@mainframe:~# intro 1
[USER]: value.toLowerCase is not a function
TypeError: value.toLowerCase is not a function
    at $.terminal.intro (http://localhost:8888/static/js/pages/upgrades/federal_reserve.js:264:35)
    at Object.interpreter (http://localhost:8888/static/js/libs/terminal.min.js:89:330)
    at Object.H [as commands] (http://localhost:8888/static/js/libs/terminal.min.js:97:173)
    at HTMLHtmlElement.x (http://localhost:8888/static/js/libs/terminal.min.js:42:175)
    at HTMLHtmlElement.x.event.dispatch (http://localhost:8888/static/js/jquery.min.js:4:10006)
    at HTMLHtmlElement.y.handle (http://localhost:8888/static/js/jquery.min.js:4:6789)
```
A simple change in `federal_reserve.js` should be all that's needed here:
```js
intro: function(value) {
    if (value != undefined) {
        value = String(value).toLowerCase();
        }
[...]
```
or, if you prefer, `value = value.toString().toLowerCase();`. This will cause a javascript error if `value` is ever `null`.

**Comment by moloch--** [comment]
@F13 added you as a collaborator, you can keep submitting pull requests or just push directly to the repo now.

**Comment by F13** [comment]
Sounds good. I know the changes are very minor, but I thought I'd see what you prefer - I assume minor changes now, consider updating the library later?
