### ISSUE TITLE
error during user registration

### ISSUE THREAD

**Issue by lucamemini** [moloch--/RootTheBox#173]
Hello moloch :-)
I have one problem during user registration with last version of RootTheBox, the webserver replay to my POST with  :
"404 - Four oh Four!?!
It looks like you typed a URL incorrectly, or were attempting to find something you ought not have access to.
The only other possibility is that I messed up some of the code, and that doesn't seem very likely."

On backand I have this stack trace:

```
[E 181004 13:38:14 web:1670] Uncaught exception POST /registration (192.168.168.5)
    HTTPServerRequest(protocol='http', host='192.168.168.21', method='POST', uri='/registration', version='HTTP/1.1', remote_ip='192.168.168.5')
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/RootTheBox/handlers/PublicHandlers.py", line 161, in post
        self.render('public/registration.html', errors=[str(error)])
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 766, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 907, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 346, in generate
        return execute()
      File "public/registration_html.generated.py", line 138, in _tt_execute
        if not suspend:  # public/registration.html:86 (via main.html:31)
    NameError: global name 'suspend' is not defined
[E 181004 13:38:14 BaseHandlers:191] Request from 192.168.168.5 resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/RootTheBox/handlers/PublicHandlers.py", line 161, in post
        self.render('public/registration.html', errors=[str(error)])
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 766, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 907, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 346, in generate
        return execute()
      File "public/registration_html.generated.py", line 138, in _tt_execute
        if not suspend:  # public/registration.html:86 (via main.html:31)
    NameError: global name 'suspend' is not defined

[E 181004 13:38:14 web:2162] 500 POST /registration (192.168.168.5) 1065.63ms
```

The system is Ubuntu xenial :)

Thankyou for your time :-)

l.

**Comment by jeffg2k** [comment]
Thanks for the report - Fixed https://github.com/moloch--/RootTheBox/commit/b85b4b3a3e39ce5450005163b993aec03252fb6a
