### ISSUE TITLE
404 on correct submission

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#187]
I recently ran a CTF and on one box, each of the 5 flags gave a 404 on a correct submission. However when going back and re-submitting accepted it correctly the second time around. It did this for every flag on the box consistently but only that one box. I grabbed the following output (the second POST was the success). Every flag was static however many contained special characters (if that makes any difference) as it was a password cracking box.

```
[I 181115 16:14:30 MissionsHandler:212] test (test) capture the flag 'P@ssw0rd #1'
[E 181115 16:14:30 web:1670] Uncaught exception POST /user/missions/capture (x.x.x.x)
    HTTPServerRequest(protocol='http', host='x.x.x.x:1337', method='POST', uri='/user/missions/capture', version='HTTP/1.1', remote_ip='x.x.x.x')
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/xxx/RootTheBox/libs/SecurityDecorators.py", line 38, in wrapper
        return method(self, *args, **kwargs)
      File "/home/xxx/RootTheBox/handlers/MissionsHandler.py", line 96, in post
        success = self.success_capture(flag)
      File "/home/xxx/RootTheBox/handlers/MissionsHandler.py", line 167, in success_capture
        if next_level._type == "progress" and level_progress * 100 >= next_level.buyout and next_level not in user.team.game_levels:
    AttributeError: 'NoneType' object has no attribute '_type'
[E 181115 16:14:30 BaseHandlers:191] Request from x.x.x.x resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/xxx/RootTheBox/libs/SecurityDecorators.py", line 38, in wrapper
        return method(self, *args, **kwargs)
      File "/home/xxx/RootTheBox/handlers/MissionsHandler.py", line 96, in post
        success = self.success_capture(flag)
      File "/home/xxx/RootTheBox/handlers/MissionsHandler.py", line 167, in success_capture
        if next_level._type == "progress" and level_progress * 100 >= next_level.buyout and next_level not in user.team.game_levels:
    AttributeError: 'NoneType' object has no attribute '_type'

[E 181115 16:14:30 web:2162] 500 POST /user/missions/capture (10.233.1.11) 61.89ms
[I 181115 16:14:30 web:2162] 101 GET /connect/notifications/updates (10.233.1.11) 0.37ms
[I 181115 16:14:41 web:2162] 101 GET /connect/notifications/updates (10.233.1.11) 0.38ms
[I 181115 16:14:49 web:2162] 200 POST /user/missions/capture (10.233.1.11) 19.53ms
```

**Comment by jeffg2k** [comment]
Thanks for the report - I've fixed the check for level progress.  I believe that the submission was actually successful the first time, but they got a 404 due to the level check.  On the second go, it didn't have to make that check because the flag was already captured and no further points / progress was made, thus giving the appearance of success on the second go.

**Comment by jeffg2k** [comment]
If you're running RTB 2.1 and you pull the latest code for 2.2, you'll need to make a DB update.  Here is the SQL.
```
ALTER TABLE `rootthebox`.`box` 
ADD COLUMN `flag_submission_type` enum('CLASSIC','SINGLE_SUBMISSION_BOX') DEFAULT 'CLASSIC' AFTER `garbage`;
```

**Comment by stealthsploit** [comment]
Appreciate the help, thanks.
