### ISSUE TITLE
Unable to delate multiple choice flag

### ISSUE THREAD

**Issue by lucamemini** [moloch--/RootTheBox#194]
Hello,
with latest version from git is impossible to delete "multiple choice" flag

Here my stack trace.

`[I 181130 22:05:22 AdminGameObjectHandlers:764] Deleted flag: Multiple Choice
[E 181130 22:05:22 web:1670] Uncaught exception POST /admin/delete/flag (127.0.0.1)
    HTTPServerRequest(protocol='http', host='ctf.malcert.com', method='POST', uri='/admin/delete/flag', version='HTTP/1.0', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/RootTheBox/libs/SecurityDecorators.py", line 63, in wrapper
        return method(self, *args, **kwargs)
      File "/home/RootTheBox/libs/SecurityDecorators.py", line 38, in wrapper
        return method(self, *args, **kwargs)
      File "/home/RootTheBox/libs/SecurityDecorators.py", line 93, in wrapper
        return method(self, *args, **kwargs)
      File "/home/RootTheBox/handlers/AdminHandlers/AdminGameObjectHandlers.py", line 740, in post
        uri[args[0]]()
      File "/home/RootTheBox/handlers/AdminHandlers/AdminGameObjectHandlers.py", line 766, in del_flag
        self.dbsession.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 954, in commit
        self.transaction.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 467, in commit
        self._prepare_impl()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
        self.session.flush()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2313, in flush
        self._flush(objects)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2440, in _flush
        transaction.rollback(_capture_exception=True)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2404, in _flush
        flush_context.execute()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
        rec.execute(self)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
        uow
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
        mapper, table, update)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 774, in _emit_update_statements
        execute(statement, multiparams)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
        return meth(self, multiparams, params)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
        context)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
        exc_info
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
        context)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 105, in do_executemany
        rowcount = cursor.executemany(statement, parameters)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 258, in executemany
        r = r + self.execute(query, a)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
        self.errorhandler(self, exc, value)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorvalue
    IntegrityError: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`rootthebox`.`flag_choice`, CONSTRAINT `flag_choice_ibfk_1` FOREIGN KEY (`flag_id`) REFERENCES `flag` (`id`))') [SQL: u'UPDATE flag_choice SET flag_id=%s WHERE flag_choice.id = %s'] [parameters: ((None, 5L), (None, 6L), (None, 7L))] (Background on this error at: http://sqlalche.me/e/gkpj)
[E 181130 22:05:22 BaseHandlers:192] Request from 127.0.0.1 resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/RootTheBox/libs/SecurityDecorators.py", line 63, in wrapper
        return method(self, *args, **kwargs)
      File "/home/RootTheBox/libs/SecurityDecorators.py", line 38, in wrapper
        return method(self, *args, **kwargs)
      File "/home/RootTheBox/libs/SecurityDecorators.py", line 93, in wrapper
        return method(self, *args, **kwargs)
      File "/home/RootTheBox/handlers/AdminHandlers/AdminGameObjectHandlers.py", line 740, in post
        uri[args[0]]()
      File "/home/RootTheBox/handlers/AdminHandlers/AdminGameObjectHandlers.py", line 766, in del_flag
        self.dbsession.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 954, in commit
        self.transaction.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 467, in commit
        self._prepare_impl()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
        self.session.flush()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2313, in flush
        self._flush(objects)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2440, in _flush
        transaction.rollback(_capture_exception=True)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2404, in _flush
        flush_context.execute()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
        rec.execute(self)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
        uow
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
        mapper, table, update)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 774, in _emit_update_statements
        execute(statement, multiparams)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
        return meth(self, multiparams, params)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
        context)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
        exc_info
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
        context)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 105, in do_executemany
        rowcount = cursor.executemany(statement, parameters)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 258, in executemany
        r = r + self.execute(query, a)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
        self.errorhandler(self, exc, value)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorvalue
    IntegrityError: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`rootthebox`.`flag_choice`, CONSTRAINT `flag_choice_ibfk_1` FOREIGN KEY (`flag_id`) REFERENCES `flag` (`id`))') [SQL: u'UPDATE flag_choice SET flag_id=%s WHERE flag_choice.id = %s'] [parameters: ((None, 5L), (None, 6L), (None, 7L))] (Background on this error at: http://sqlalche.me/e/gkpj)

[E 181130 22:05:22 BaseHandlers:87] Failed call to get_current_user()
    Traceback (most recent call last):
      File "/home/RootTheBox/handlers/BaseHandlers.py", line 83, in get_current_user
        return User.by_uuid(self.session['user_uuid'])
      File "/home/RootTheBox/models/User.py", line 134, in by_uuid
        return dbsession.query(cls).filter_by(uuid=unicode(_uuid)).first()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2895, in first
        ret = list(self[0:1])
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
        return list(res)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
        return self._execute_and_instances(context)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3016, in _execute_and_instances
        close_with_result=True)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3025, in _get_bind_args
        **kw
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3007, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1046, in connection
        execution_options=execution_options)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1051, in _connection_for_bind
        engine, execution_options)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
        self._assert_active()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`rootthebox`.`flag_choice`, CONSTRAINT `flag_choice_ibfk_1` FOREIGN KEY (`flag_id`) REFERENCES `flag` (`id`))') [SQL: u'UPDATE flag_choice SET flag_id=%s WHERE flag_choice.id = %s'] [parameters: ((None, 5L), (None, 6L), (None, 7L))] (Background on this error at: http://sqlalche.me/e/gkpj)
[E 181130 22:05:22 web:1114] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1112, in send_error
        self.write_error(status_code, **kwargs)
      File "/home/RootTheBox/handlers/BaseHandlers.py", line 202, in write_error
        self.render('public/404.html')
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 766, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 907, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 346, in generate
        return execute()
      File "public/404_html.generated.py", line 14, in _tt_execute
        _tt_tmp = _tt_modules.Menu()  # main.html:29
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1678, in render
        rendered = self._active_modules[name].render(*args, **kwargs)
      File "/home/RootTheBox/modules/Menu.py", line 35, in render
        user = User.by_id(self.handler.session['user_id'])
      File "/home/RootTheBox/models/User.py", line 129, in by_id
        return dbsession.query(cls).filter_by(id=_id).first()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2895, in first
        ret = list(self[0:1])
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
        return list(res)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
        return self._execute_and_instances(context)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3016, in _execute_and_instances
        close_with_result=True)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3025, in _get_bind_args
        **kw
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3007, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1046, in connection
        execution_options=execution_options)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1051, in _connection_for_bind
        engine, execution_options)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
        self._assert_active()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`rootthebox`.`flag_choice`, CONSTRAINT `flag_choice_ibfk_1` FOREIGN KEY (`flag_id`) REFERENCES `flag` (`id`))') [SQL: u'UPDATE flag_choice SET flag_id=%s WHERE flag_choice.id = %s'] [parameters: ((None, 5L), (None, 6L), (None, 7L))] (Background on this error at: http://sqlalche.me/e/gkpj)
[E 181130 22:05:22 web:2162] 500 POST /admin/delete/flag (127.0.0.1) 24.25ms
`

**Comment by jeffg2k** [comment]
Thanks for the report @lucamemini I've pushed a fix that I think should fix it.  Please give it a test when you get a chance.

**Comment by lucamemini** [comment]
THX ! 
work perfectly :-)

l.
