### ISSUE TITLE
Reset game doesn't clean the scoreboard history

### ISSUE THREAD

**Issue by garanews** [moloch--/RootTheBox#205]
Reset game doesn't clean the scoreboard history.

**Comment by garanews** [comment]
As workaround is it safe to clean these tables?

| snapshot                    |
| snapshot_team               |
| snapshot_team_to_flag       |
| snapshot_team_to_game_level |
| snapshot_to_snapshot_team |

**Comment by garanews** [comment]
probably is enough clean memcache:

`echo 'flush_all' | nc localhost 11211
`
can you confirm?

**Comment by jeffg2k** [comment]
There are a lot of key dependencies tied into the history and snapshots.  I think it would be safe to clear them, but haven't tested this out myself.  I'm not sure what would need to change on the DB to allow an easy deletion.  Let me know if it works

**Comment by dadokkio** [comment]
We tried both solution and all of them cleared the scoreboard history.
In the first case we truncated all the tables (with foreign key constraint disabled) but we had to fix also the GameHistory.py lib because the __len__ function starts to raise error.
The second (memcache flush) seems to be better but we need to check if everything is still working properly.


In both cases (but we are not sure if it's related or was the normal behaviour) we are having issue with the websocket in history page:
![image](https://user-images.githubusercontent.com/355183/49633541-f5c06600-f9f9-11e8-8ddc-3fe08c9b9223.png)
```
[E 181207 08:34:02 web:1670] Uncaught exception GET /scoreboard/wsocket/game_history?length=29 
    HTTPServerRequest(protocol='http', host='', method='GET', uri='/scoreboard/wsocket/game_history?length=29', version='HTTP/1.1', remote_ip='')
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 546, in _run_callback
        result = callback(*args, **kwargs)
      File "/home/thehive/RootTheBox-master/handlers/ScoreboardHandlers.py", line 192, in on_message
        self.write_message(self.game_history[:-1])
      File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 262, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 854, in write_message
        message = tornado.escape.utf8(message)
      File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 197, in utf8
        "Expected bytes, unicode, or None; got %r" % type(value)
    TypeError: Expected bytes, unicode, or None; got <type 'list'>

**Comment by garanews** [comment]
This #207 should fix the socket error
