### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by mohammadHmedat** [moloch--/RootTheBox#208]
when i setup the the app i get that error

/RootTheBox$ sudo ./rootthebox.py --setup=prod
[*] 11:37:27 : Creating the database ...
[D 181211 11:37:27 DatabaseConnection:70] Configured to use MySQL for a database
[I 181211 11:37:27 migration:117] Context impl MySQLImpl.
[I 181211 11:37:27 migration:122] Will assume non-transactional DDL.
[I 181211 11:37:27 migration:327] Running upgrade  -> 9783dbd4d5fe, add original_value
Traceback (most recent call last):
  File "./rootthebox.py", line 592, in <module>
    setup()
  File "./rootthebox.py", line 65, in setup
    from setup.create_database import create_tables, engine, metadata
  File "/home/ubuntu/RootTheBox/setup/create_database.py", line 21, in <module>
    from models import engine
  File "/home/ubuntu/RootTheBox/models/__init__.py", line 66, in <module>
    command.upgrade(alembic_cfg, "head")
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 198, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "alembic/env.py", line 71, in <module>
    run_migrations_online()
  File "alembic/env.py", line 66, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/home/ubuntu/RootTheBox/alembic/versions/9783dbd4d5fe_add_original_value.py", line 22, in upgrade
    type_=sa.VARCHAR(length=1024))
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations/ops.py", line 1444, in alter_column
    return operations.invoke(alt)
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations/base.py", line 319, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations/toimpl.py", line 53, in alter_column
    **operation.kw
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/mysql.py", line 68, in alter_column
    else existing_autoincrement
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 115, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'rootthebox.hint' doesn't exist") [SQL: u'ALTER TABLE hint MODIFY _description VARCHAR(1024) NULL'] (Background on this error at: http://sqlalche.me/e/f405)

**Comment by jeffg2k** [comment]
Opps, forgot to stamp the head for a new creation.  Pushed an update - give it a try now.

**Comment by jeffg2k** [comment]
You'll need to drop the tables and rerun --setup.
