### ISSUE TITLE
Error when exporting complete XML file

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#217]
When exporting the complete game with all objects, I keep getting a 404 with the following error. Any help would be appreciated, thanks.

```
[I 190214 15:41:53 web:2162] 200 GET /admin/export/xml (xx.xx.xx.xx) 12.72ms
[I 190214 15:41:53 web:2162] 101 GET /connect/notifications/updates (xx.xx.xx.xx) 0.61ms
[E 190214 15:41:55 web:1670] Uncaught exception POST /admin/export/xml (xx.xx.xx.xx)
    HTTPServerRequest(protocol='http', host='xx.xx.xx.xx:1337', method='POST', uri='/admin/export/xml', version='HTTP/1.1', remote_ip='xx.xx.xx.xx')
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/ex-platform/RootTheBox/libs/SecurityDecorators.py", line 63, in wrapper
        return method(self, *args, **kwargs)
      File "/home/ex-platform/RootTheBox/libs/SecurityDecorators.py", line 38, in wrapper
        return method(self, *args, **kwargs)
      File "/home/ex-platform/RootTheBox/libs/SecurityDecorators.py", line 93, in wrapper
        return method(self, *args, **kwargs)
      File "/home/ex-platform/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 426, in post
        self.export_game_objects(root)
      File "/home/ex-platform/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 457, in export_game_objects
        corp.to_xml(corps_elem)
      File "/home/ex-platform/RootTheBox/models/Corporation.py", line 99, in to_xml
        box.to_xml(boxes_elem)
      File "/home/ex-platform/RootTheBox/models/Box.py", line 289, in to_xml
        with open(options.avatar_dir + '/' + self.avatar, mode='rb') as _avatar:
    IOError: [Errno 2] No such file or directory: './files/avatars/none'
[E 190214 15:41:55 BaseHandlers:196] Request from xx.xx.xx.xx resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/ex-platform/RootTheBox/libs/SecurityDecorators.py", line 63, in wrapper
        return method(self, *args, **kwargs)
      File "/home/ex-platform/RootTheBox/libs/SecurityDecorators.py", line 38, in wrapper
        return method(self, *args, **kwargs)
      File "/home/ex-platform/RootTheBox/libs/SecurityDecorators.py", line 93, in wrapper
        return method(self, *args, **kwargs)
      File "/home/ex-platform/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 426, in post
        self.export_game_objects(root)
      File "/home/ex-platform/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 457, in export_game_objects
        corp.to_xml(corps_elem)
      File "/home/ex-platform/RootTheBox/models/Corporation.py", line 99, in to_xml
        box.to_xml(boxes_elem)
      File "/home/ex-platform/RootTheBox/models/Box.py", line 289, in to_xml
        with open(options.avatar_dir + '/' + self.avatar, mode='rb') as _avatar:
    IOError: [Errno 2] No such file or directory: './files/avatars/none'

[E 190214 15:41:55 web:2162] 500 POST /admin/export/xml (xx.xx.xx.xx) 56.73ms
[I 190214 15:41:55 web:2162] 101 GET /connect/notifications/updates (xx.xx.xx.xx) 0.99ms

```

**Comment by jeffg2k** [comment]
Thanks for the report - I'll look at it soon.  I have to rebuild my VM.  Apparently, I created my RTB VM as a linked clone and I deleted the base vm. :/  Oh well.  Time to rebuild it and make sure setup works good.

**Comment by jeffg2k** [comment]
@stealthsploit I pushed an update - please give it a try.

**Comment by stealthsploit** [comment]
Thanks @jeffg2k for the prompt fix. Works perfectly. Glad your VM is back up and running@
