### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mohammadHmedat** [moloch--/RootTheBox#220]
hello all

I have an old version from rootthebox, today I installed the latest version in another folder to see the updates and new features it works fine with the old DB but when I run the old version I have this problem, help please:

Traceback (most recent call last):
  File "./rootthebox.py", line 600, in <module>
    start()
  File "./rootthebox.py", line 43, in start
    from handlers import start_server
  File "/home/ubuntu/RootTheBox/handlers/__init__.py", line 31, in <module>
    from modules.Menu import Menu
  File "/home/ubuntu/RootTheBox/modules/Menu.py", line 24, in <module>
    from models.User import User
  File "/home/ubuntu/RootTheBox/models/__init__.py", line 66, in <module>
    command.upgrade(alembic_cfg, "head")
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 216, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "alembic/env.py", line 71, in <module>
    run_migrations_online()
  File "alembic/env.py", line 66, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 350, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 265, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 365, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 190, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(resolution))
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 289, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 158, in _catch_revision_errors
    yield
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 360, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 740, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 318, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 323, in get_revisions
    for rev_id in resolved_id
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 323, in <genexpr>
    for rev_id in resolved_id
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 386, in _revision_for_ident
    resolved_id,
alembic.util.exc.CommandError: Can't locate revision identified by 'eb3f7dc1b16f'

**Comment by jeffg2k** [comment]
Yeah, so the new version most likely updated the database schema.  When an update is performed, an alembic file is created and entry added to the database so it knows the change history and what it may need to do.  Try to copy the files in the alembic/versions directory into your old versions alembic/versions directory.  It's probably missing one or more of the files. https://github.com/moloch--/RootTheBox/tree/master/alembic/versions

**Comment by mohammadHmedat** [comment]
after i add the versions fils

[*] 13:51:52 : Creating the database ...
[I 190221 13:51:52 migration:130] Context impl MySQLImpl.
[I 190221 13:51:52 migration:137] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "./rootthebox.py", line 598, in <module>
    setup()
  File "./rootthebox.py", line 65, in setup
    from setup.create_database import create_tables, engine, metadata
  File "/home/ubuntu/RootTheBox/setup/create_database.py", line 21, in <module>
    from models import engine
  File "/home/ubuntu/RootTheBox/models/__init__.py", line 66, in <module>
    command.upgrade(alembic_cfg, "head")
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 216, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "alembic/env.py", line 71, in <module>
    run_migrations_online()
  File "alembic/env.py", line 66, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 350, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 265, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 360, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 740, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 318, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 320, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 476, in _resolve_revision_number
    self._revision_map
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/langhelpers.py", line 247, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/revision.py", line 123, in _revision_map
    for revision in self._generator():
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 109, in _load_revisions
    script = Script._from_filename(self, vers, file_)
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 887, in _from_filename
    module = util.load_python_file(dir_, filename)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 216, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/home/ubuntu/RootTheBox/alembic/versions/eb3f7dc1b16f_add_flag__order_field.py", line 23
    op.drop_column('flag', '_order')
     ^
IndentationError: expected an indented block

**Comment by mohammadHmedat** [comment]
done fixed thanks
