### ISSUE TITLE
Change Scoreboard 

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#255]
Hey :D 
I am setting up CTF using ur Platform and I changed the Scoreboard from Public to Players I got this error below 
```python
[E 190716 20:13:46 web:1670] Uncaught exception POST /admin/configuration (91.74.18.231)
    HTTPServerRequest(protocol='https', host='labs.saluslab.net', method='POST', uri='/admin/configuration', version='HTTP/1.1', remote_ip='91.74.18.231')
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
        return method(self, *args, **kwargs)
      File "/root/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
        return method(self, *args, **kwargs)
      File "/root/RootTheBox/libs/SecurityDecorators.py", line 108, in wrapper
        return method(self, *args, **kwargs)
      File "/root/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 365, in post
        self.config.rank_by = str(self.get_argument("rank_by", "money"))
      File "/usr/local/lib/python2.7/dist-packages/tornado/options.py", line 141, in __setattr__
        return self._options[name].set(value)
      File "/usr/local/lib/python2.7/dist-packages/tornado/options.py", line 535, in set
        (self.name, self.type.__name__, type(value)))
    Error: Option 'rank_by' is required to be a str (<class 'future.types.newstr.newstr'> given)
[E 190716 20:13:46 BaseHandlers:195] Request from 91.74.18.231 resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
        return method(self, *args, **kwargs)
      File "/root/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
        return method(self, *args, **kwargs)
      File "/root/RootTheBox/libs/SecurityDecorators.py", line 108, in wrapper
        return method(self, *args, **kwargs)
      File "/root/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 365, in post
        self.config.rank_by = str(self.get_argument("rank_by", "money"))
      File "/usr/local/lib/python2.7/dist-packages/tornado/options.py", line 141, in __setattr__
        return self._options[name].set(value)
      File "/usr/local/lib/python2.7/dist-packages/tornado/options.py", line 535, in set
        (self.name, self.type.__name__, type(value)))
    Error: Option 'rank_by' is required to be a str (<class 'future.types.newstr.newstr'> given)

[E 190716 20:13:46 web:2162] 500 POST /admin/configuration (91.74.18.231) 48.23ms
```
any help 😄

**Comment by jeffg2k** [comment]
Fixed - Python2 didn't like the builtins str
