### ISSUE TITLE
Unlock Level issues

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#277]
Hi I have a small issue with level unlock during the CTF Player were given bonus points to unlock CTF level but then when they tried to unlock it gave an error 
```shell
[E 190924 09:30:28 web:1670] Uncaught exception POST /user/missions/buyout (172.27.232.2)
    HTTPServerRequest(protocol='http', host='192.168.70.109', method='POST', uri='/user/missions/buyout', version='HTTP/1.1', remote_ip='172.27.232.2')
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
        return method(self, *args, **kwargs)
      File "/root/RootTheBox/handlers/MissionsHandler.py", line 535, in post
        uri[str(args[0])]()
      File "/root/RootTheBox/handlers/MissionsHandler.py", line 553, in buyout
        % (user.handle, user.team.name, level.name)
    TypeError: %d format: a number is required, not unicode
[E 190924 09:30:28 BaseHandlers:196] Request from 172.27.232.2 resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
        return method(self, *args, **kwargs)
      File "/root/RootTheBox/handlers/MissionsHandler.py", line 535, in post
        uri[str(args[0])]()
      File "/root/RootTheBox/handlers/MissionsHandler.py", line 553, in buyout
        % (user.handle, user.team.name, level.name)
    TypeError: %d format: a number is required, not unicode
    
[E 190924 09:30:28 web:2162] 500 POST /user/missions/buyout (172.27.232.2) 30.81ms
```
attached the steps that I did 
1) Giving Points via Game Management -> Teams 
![image](https://user-images.githubusercontent.com/16447622/65500333-34170b00-ded0-11e9-884c-9ddc19c1d84b.png)

2) Level Details 
![image](https://user-images.githubusercontent.com/16447622/65500286-22cdfe80-ded0-11e9-86ef-59d99728705c.png)

As Player When I purchase the level I go this Error Msg
![image](https://user-images.githubusercontent.com/16447622/65500242-0df16b00-ded0-11e9-8bb4-689d7840c75f.png)

**Comment by jeffg2k** [comment]
Pushed a fix for this if you can test it out.
