### ISSUE TITLE
[E 190926 16:53:15 rootthebox:52] Error: Could not parse rfc1738 URL from string 

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#278]
```
root@Main-Droplet:~/Forces# python3 rootthebox.py --setup=prod
[*] 16:38:38 : Creating the database ...
[*] 16:38:38 : Bootstrapping the database ...
[?] RootTheBox Admin Username [admin]: admin
[?] New Admin Password:
[?] Confirm New Admin Password:
[I 190926 16:39:03 GameHistory:55] Loading game history from database ...
[I 190926 16:39:03 GameHistory:72] History load complete.
Traceback (most recent call last):
  File "rootthebox.py", line 806, in <module>
    setup()
  File "rootthebox.py", line 100, in setup
    update_db(False)
  File "/root/Forces/handlers/__init__.py", line 262, in update_db
    command.stamp(alembic_cfg, "head")
  File "/usr/local/lib/python3.6/dist-packages/alembic/command.py", line 579, in stamp
    script.run_env()
  File "/usr/local/lib/python3.6/dist-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic/env.py", line 72, in <module>
    run_migrations_online()
  File "alembic/env.py", line 59, in run_migrations_online
    poolclass=pool.NullPool,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/__init__.py", line 499, in engine_from_config
    return create_engine(url, **options)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/__init__.py", line 456, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'mysql pymysql://(User):(Pass)@localhost/(dbname)?charset=utf8mb4'
root@Main-Droplet:~/Forces# python3 rootthebox.py --start
[I 190926 16:53:15 GameHistory:55] Loading game history from database ...
[I 190926 16:53:15 GameHistory:72] History load complete.
[E 190926 16:53:15 rootthebox:52] Error: Could not parse rfc1738 URL from string 'mysql pymysql://(User):(Pass)@localhost/(dbname)?charset=utf8mb4'

```

**Comment by CovertError** [comment]
It's the latest version and I'm running it on ubuntu 18

**Comment by jeffg2k** [comment]
Should be fix now with the latest commit - thanks for the report.
