### ISSUE TITLE
User Creation Error

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#286]
when creating new users now I keep getting this I tried getting a fresh install and the same problem is happening.

```
404 - Glitch in the Matrix

It looks like you typed a URL incorrectly, or were attempting to find something you ought not have access to.
The only other possibility is that I messed up some of the code, and that doesn't seem very likely.
```

```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/RootTheBox/handlers/PublicHandlers.py", line 187, in post
        user = self.create_user()
      File "/root/RootTheBox/handlers/PublicHandlers.py", line 215, in create_user
        user.bank_password = self.get_argument("bpass", "")
      File "/root/RootTheBox/models/User.py", line 189, in bank_password
        self._bank_password = self._hash_bank_password(self.algorithm, _password)
      File "/root/RootTheBox/models/User.py", line 145, in _hash_bank_password
        algo.update(encode(password))
      File "/root/RootTheBox/libs/StringCoding.py", line 38, in encode
        rv, length = codec.encode(s, *args, **kwargs)
    TypeError: utf_8_encode() argument 1 must be str, not list
```

**Comment by jeffg2k** [comment]
Matrix glitch fixed.  Thanks for the report.
