### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#289]
```
Oct 10 17:36:01 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         result = method(*self.path_args, **self.path_kwargs)
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/root/rtb/libs/SecurityDecorators.py", line 46, in wrapper
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         return method(self, *args, **kwargs)
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/UserHandlers.py", line 80, in post
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         post_functions[args[0]]()
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/UserHandlers.py", line 223, in post_bankpassword
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         if self.config.recaptcha_enabled:
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/options.py", line 145, in __getattr__
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         raise AttributeError("Unrecognized option %r" % name)
Oct 10 17:36:01 DO-Droplet python3.6[1034]:     AttributeError: Unrecognized option 'recaptcha-enabled'
Oct 10 17:36:01 DO-Droplet python3.6[1034]: [E 191010 17:36:01 BaseHandlers:196] Request from 5.108.26.128 resulted in an error code 500:
Oct 10 17:36:01 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         result = method(*self.path_args, **self.path_kwargs)
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/root/rtb/libs/SecurityDecorators.py", line 46, in wrapper
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         return method(self, *args, **kwargs)
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/UserHandlers.py", line 80, in post
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         post_functions[args[0]]()
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/UserHandlers.py", line 223, in post_bankpassword
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         if self.config.recaptcha_enabled:
Oct 10 17:36:01 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/options.py", line 145, in __getattr__
Oct 10 17:36:01 DO-Droplet python3.6[1034]:         raise AttributeError("Unrecognized option %r" % name)
Oct 10 17:36:01 DO-Droplet python3.6[1034]:     AttributeError: Unrecognized option 'recaptcha-enabled'
```

**Comment by jeffg2k** [comment]
Fixed this, but there will still be a problem with using recaptcha.  We haven't updated it after Google shut down captcha v1.  Need to upgrade it to v2 or v3. #233
