### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#290]
```
Oct 10 17:38:47 DO-Droplet python3.6[1034]: [E 191010 17:38:47 web:1788] Uncaught exception GET /user (51.253.251.224)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:     HTTPServerRequest(protocol='https', host='DO.tech:8888', method='GET', uri='/user', version='HTTP/1.1', remote_ip='51.253.251.224')
Oct 10 17:38:47 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         result = method(*self.path_args, **self.path_kwargs)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/root/rtb/libs/SecurityDecorators.py", line 46, in wrapper
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         return method(self, *args, **kwargs)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/UserHandlers.py", line 57, in get
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         self.render("user/home.html", user=user, game_started=game_started)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         html = self.render_string(template_name, **kwargs)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         return t.generate(**namespace)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         return execute()
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "user/home_html.generated.py", line 26, in _tt_execute
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         _tt_tmp = _tt_modules.Menu()  # main.html:30
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         rendered = self._active_modules[name].render(*args, **kwargs)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/root/rtb/modules/Menu.py", line 43, in render
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         "menu/user.html", user=user, scoreboard_visible=scoreboard_visible
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         return self.handler.render_string(path, **kwargs)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         return t.generate(**namespace)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         return execute()
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "menu/user_html.generated.py", line 137, in _tt_execute
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         if len(user.team.items) != 0:  # menu/user.html:107
Oct 10 17:38:47 DO-Droplet python3.6[1034]:     AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by CovertError** [comment]
This looks like its related to the score board maybe not sure
```
Oct 10 17:39:18 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         result = method(*self.path_args, **self.path_kwargs)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/root/rtb/libs/SecurityDecorators.py", line 46, in wrapper
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return method(self, *args, **kwargs)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/UserHandlers.py", line 57, in get
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         self.render("user/home.html", user=user, game_started=game_started)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         html = self.render_string(template_name, **kwargs)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return t.generate(**namespace)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return execute()
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "user/home_html.generated.py", line 26, in _tt_execute
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         _tt_tmp = _tt_modules.Menu()  # main.html:30
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         rendered = self._active_modules[name].render(*args, **kwargs)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/root/rtb/modules/Menu.py", line 43, in render
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         "menu/user.html", user=user, scoreboard_visible=scoreboard_visible
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return self.handler.render_string(path, **kwargs)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return t.generate(**namespace)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return execute()
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "menu/user_html.generated.py", line 137, in _tt_execute
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         if len(user.team.items) != 0:  # menu/user.html:107
Oct 10 17:39:18 DO-Droplet python3.6[1034]:     AttributeError: 'NoneType' object has no attribute 'items'
Oct 10 17:39:18 DO-Droplet python3.6[1034]:     
Oct 10 17:39:18 DO-Droplet python3.6[1034]:     During handling of the above exception, another exception occurred:
Oct 10 17:39:18 DO-Droplet python3.6[1034]:     
Oct 10 17:39:18 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1214, in send_error
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         self.write_error(status_code, **kwargs)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/BaseHandlers.py", line 206, in write_error
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         self.render("public/404.html")
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         html = self.render_string(template_name, **kwargs)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return t.generate(**namespace)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return execute()
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "public/404_html.generated.py", line 14, in _tt_execute
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         _tt_tmp = _tt_modules.Menu()  # main.html:30
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         rendered = self._active_modules[name].render(*args, **kwargs)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/root/rtb/modules/Menu.py", line 43, in render
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         "menu/user.html", user=user, scoreboard_visible=scoreboard_visible
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return self.handler.render_string(path, **kwargs)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return t.generate(**namespace)
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         return execute()
Oct 10 17:39:18 DO-Droplet python3.6[1034]:       File "menu/user_html.generated.py", line 137, in _tt_execute
Oct 10 17:39:18 DO-Droplet python3.6[1034]:         if len(user.team.items) != 0:  # menu/user.html:107
Oct 10 17:39:18 DO-Droplet python3.6[1034]:     AttributeError: 'NoneType' object has no attribute 'items'
```
