### ISSUE TITLE
Notification Related Error

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#291]
```
Oct 10 17:38:47 DO-Droplet python3.6[1034]: [E 191010 17:38:47 ioloop:763] Exception in callback functools.partial(<bound method EventManager.remove_connection of <libs.EventManager.EventManager object at 0x7fd6b6d4f518>>, <handlers.NotificationHandlers.NotifySocketHandler object at 0x7fd6b5c7fb38>)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 743, in _run_callback
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         ret = callback()
Oct 10 17:38:47 DO-Droplet python3.6[1034]:       File "/root/rtb/libs/EventManager.py", line 72, in remove_connection
Oct 10 17:38:47 DO-Droplet python3.6[1034]:         team_connections[connection.user_id].remove(connection)
Oct 10 17:38:47 DO-Droplet python3.6[1034]:     KeyError: <handlers.NotificationHandlers.NotifySocketHandler object at 0x7fd6b5c7fb38>
```

**Comment by CovertError** [comment]
This might be related not sure
```
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.6/dist-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:36 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1104, in wrapper
Oct 10 17:48:36 DO-Droplet python3.6[1034]:         await fut
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     tornado.iostream.StreamClosedError: Stream is closed
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     During handling of the above exception, another exception occurred:
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:36 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1106, in wrapper
Oct 10 17:48:36 DO-Droplet python3.6[1034]:         raise WebSocketClosedError()
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     tornado.websocket.WebSocketClosedError
Oct 10 17:48:36 DO-Droplet python3.6[1034]: [E 191010 17:48:36 base_events:1285] Task exception was never retrieved
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.6/dist-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:36 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1104, in wrapper
Oct 10 17:48:36 DO-Droplet python3.6[1034]:         await fut
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     tornado.iostream.StreamClosedError: Stream is closed
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     During handling of the above exception, another exception occurred:
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:36 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1106, in wrapper
Oct 10 17:48:36 DO-Droplet python3.6[1034]:         raise WebSocketClosedError()
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     tornado.websocket.WebSocketClosedError
Oct 10 17:48:36 DO-Droplet python3.6[1034]: [E 191010 17:48:36 ioloop:763] Exception in callback functools.partial(<bound method EventManager.remove_connection of <libs.EventManager.EventManager object at 0x7fd6b6d4f518>>, <handlers.NotificationHandlers.NotifySocketHandler object at 0x7fd6b5c86908>)
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:36 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 743, in _run_callback
Oct 10 17:48:36 DO-Droplet python3.6[1034]:         ret = callback()
Oct 10 17:48:36 DO-Droplet python3.6[1034]:       File "/root/rtb/libs/EventManager.py", line 72, in remove_connection
Oct 10 17:48:36 DO-Droplet python3.6[1034]:         team_connections[connection.user_id].remove(connection)
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     KeyError: <handlers.NotificationHandlers.NotifySocketHandler object at 0x7fd6b5c86908>
Oct 10 17:48:36 DO-Droplet python3.6[1034]: [E 191010 17:48:36 ioloop:763] Exception in callback functools.partial(<bound method EventManager.remove_connection of <libs.EventManager.EventManager object at 0x7fd6b6d4f518>>, <handlers.NotificationHandlers.NotifySocketHandler object at 0x7fd6b5718128>)
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:36 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 743, in _run_callback
Oct 10 17:48:36 DO-Droplet python3.6[1034]:         ret = callback()
Oct 10 17:48:36 DO-Droplet python3.6[1034]:       File "/root/rtb/libs/EventManager.py", line 72, in remove_connection
Oct 10 17:48:36 DO-Droplet python3.6[1034]:         team_connections[connection.user_id].remove(connection)
Oct 10 17:48:36 DO-Droplet python3.6[1034]:     KeyError: <handlers.NotificationHandlers.NotifySocketHandler object at 0x7fd6b5718128>
```

**Comment by CovertError** [comment]
or maybe it's related to a connection problem 
```
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.6/dist-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:43 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1104, in wrapper
Oct 10 17:48:43 DO-Droplet python3.6[1034]:         await fut
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     tornado.iostream.StreamClosedError: Stream is closed
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     During handling of the above exception, another exception occurred:
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:43 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1106, in wrapper
Oct 10 17:48:43 DO-Droplet python3.6[1034]:         raise WebSocketClosedError()
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     tornado.websocket.WebSocketClosedError
```

**Comment by CovertError** [comment]
is this fixed too?

```
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.6/dist-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:43 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1104, in wrapper
Oct 10 17:48:43 DO-Droplet python3.6[1034]:         await fut
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     tornado.iostream.StreamClosedError: Stream is closed
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     During handling of the above exception, another exception occurred:
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:43 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 1106, in wrapper
Oct 10 17:48:43 DO-Droplet python3.6[1034]:         raise WebSocketClosedError()
Oct 10 17:48:43 DO-Droplet python3.6[1034]:     tornado.websocket.WebSocketClosedError
```
