### ISSUE TITLE
Runtime Errors

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#292]
```
Oct 10 17:48:59 DO-Droplet python3.6[1034]:     HTTPServerRequest(protocol='https', host='DO.tech:8888', method='POST', uri='/user/missions/capture', version='HTTP/1.1', remote_ip='185.51.204.251')
Oct 10 17:48:59 DO-Droplet python3.6[1034]:     Traceback (most recent call last):
Oct 10 17:48:59 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Oct 10 17:48:59 DO-Droplet python3.6[1034]:         result = method(*self.path_args, **self.path_kwargs)
Oct 10 17:48:59 DO-Droplet python3.6[1034]:       File "/root/rtb/libs/SecurityDecorators.py", line 46, in wrapper
Oct 10 17:48:59 DO-Droplet python3.6[1034]:         return method(self, *args, **kwargs)
Oct 10 17:48:59 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/MissionsHandler.py", line 255, in post
Oct 10 17:48:59 DO-Droplet python3.6[1034]:         self.render_page_by_flag(flag, errors=[penalty_dialog])
Oct 10 17:48:59 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/MissionsHandler.py", line 427, in render_page_by_flag
Oct 10 17:48:59 DO-Droplet python3.6[1034]:         self.render_page_by_box_id(flag.box_id, errors, success, info)
Oct 10 17:48:59 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/MissionsHandler.py", line 431, in render_page_by_box_id
Oct 10 17:48:59 DO-Droplet python3.6[1034]:         self.render_page_by_box(box, errors, success, info)
Oct 10 17:48:59 DO-Droplet python3.6[1034]:       File "/root/rtb/handlers/MissionsHandler.py", line 443, in render_page_by_box
Oct 10 17:48:59 DO-Droplet python3.6[1034]:         info=info,
Oct 10 17:48:59 DO-Droplet python3.6[1034]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 855, in render
Oct 10 17:48:59 DO-Droplet python3.6[1034]:         raise RuntimeError("Cannot render() after finish()")
Oct 10 17:48:59 DO-Droplet python3.6[1034]:     RuntimeError: Cannot render() after finish()
```

**Comment by jeffg2k** [comment]
I think this probably happened by submitting an empty flag.  Which could have fallen through to another render.  Added returns after all the renders so this doesn't happen.
