### ISSUE TITLE
mysql Error

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#293]
```
Oct 12 13:18:08 DO-Droplet python3.6[8673]: [I 191012 10:18:08 web:2246] 302 GET /scoreboard (206.189.214.145) 3.54ms
Oct 12 13:18:08 DO-Droplet python3.6[8673]: [E 191012 10:18:08 base:689] Exception during reset or similar
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     Traceback (most recent call last):
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 713, in _write_bytes
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self._sock.sendall(data)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     BrokenPipeError: [Errno 32] Broken pipe
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     During handling of the above exception, another exception occurred:
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     Traceback (most recent call last):
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 739, in _rollback_impl
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self.engine.dialect.do_rollback(self.connection)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2253, in do_rollback
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         dbapi_connection.rollback()
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 429, in rollback
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 771, in _execute_command
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self._write_bytes(packet)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 718, in _write_bytes
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         "MySQL server has gone away (%r)" % (e,))
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     The above exception was the direct cause of the following exception:
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     Traceback (most recent call last):
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         fairy._reset(pool)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 865, in _reset
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self._reset_agent.rollback()
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1713, in rollback
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self._do_rollback()
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1751, in _do_rollback
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self.connection._rollback_impl()
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 741, in _rollback_impl
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self._handle_dbapi_exception(e, None, None, None, None)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         util.raise_from_cause(sqlalchemy_exception, exc_info)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         reraise(type(exception), exception, tb=exc_tb, cause=cause)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         raise value.with_traceback(tb)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 739, in _rollback_impl
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self.engine.dialect.do_rollback(self.connection)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2253, in do_rollback
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         dbapi_connection.rollback()
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 429, in rollback
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 771, in _execute_command
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         self._write_bytes(packet)
Oct 12 13:18:08 DO-Droplet python3.6[8673]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 718, in _write_bytes
Oct 12 13:18:08 DO-Droplet python3.6[8673]:         "MySQL server has gone away (%r)" % (e,))
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Oct 12 13:18:08 DO-Droplet python3.6[8673]:     (Background on this error at: http://sqlalche.me/e/e3q8)
Oct 12 13:18:08 DO-Droplet python3.6[8673]: [I 191012 10:18:08 web:2246] 302 GET /scoreboard (206.189.214.145) 3.02ms
```

**Comment by jeffg2k** [comment]
I've updated the database engine to do a `pool_pre_ping` when using a recycled pool connection.  This should fix the broken pipe error for mysql sockets being closed after a period of in use, which is what this appears to be.  If this is instead something you can regularly reproduce due to the scoreboard query being too large, please reopen the issue.
