### ISSUE TITLE
import xml - emoji

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#298]
I'm getting this error while trying to import an XML 
ERROR
Failed to parse file correctly.
```
Oct 26 23:58:30 CyberAgora-Droplet python3.6[11806]: [I 191026 23:58:30 xmlsetup:74] Found 1 game level(s)
Oct 26 23:58:30 CyberAgora-Droplet python3.6[11806]: [I 191026 23:58:30 xmlsetup:59] Found 0 categories
Oct 26 23:58:30 CyberAgora-Droplet python3.6[11806]: [I 191026 23:58:30 xmlsetup:211] Found 3 corporation(s)
Oct 26 23:58:30 CyberAgora-Droplet python3.6[11806]: [I 191026 23:58:30 xmlsetup:170] Found 1 boxes
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]: [E 191026 23:58:31 xmlsetup:206] Failed to import box 1 ((pymysql.err.InternalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x88' for column '_description' at row 1")
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [SQL: INSERT INTO box (created, uuid, corporation_id, category_id, _name, _operating_system, _description, _capture_message, _difficulty, game_level_id, _avatar, _value, garbage, flag_submission_type) VALUES (%(created)s, %(uuid)s, %(corporation_id)s, %(category_id)s, %(_name)s, %(_operating_system)s, %(_description)s, %(_capture_message)s, %(_difficulty)s, %(game_level_id)s, %(_avatar)s, %(_value)s, %(garbage)s, %(flag_submission_type)s)]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [parameters: {'created': datetime.datetime(2019, 10, 26, 23, 58, 30, 996633), 'uuid': '49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139', 'corporation_id': 3, 'category_id': None, '_name': 'Encryption', '_operating_system': 'none', '_description': 'Go to the web page using the IP provided and start collecting your flags and decrypting it😈', '_capture_message': '', '_difficulty': 'Easy - Medium', 'game_level_id': 1, '_avatar': 'upload/49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139.jpeg', '_value': 5, 'garbage': 'c64923f9248e39264255988b39f7ce66', 'flag_submission_type': 'CLASSIC'}]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     (Background on this error at: http://sqlalche.me/e/2j85))
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     Traceback (most recent call last):
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         cursor, statement, parameters, context
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         cursor.execute(statement, parameters)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 170, in execute
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         result = self._query(query)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 328, in _query
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         conn.query(q)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 517, in query
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         self._affected_rows = self._read_query_result(unbuffered=unbuffered)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 732, in _read_query_result
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         result.read()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1075, in read
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         first_packet = self.connection._read_packet()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         packet.check_error()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         err.raise_mysql_exception(self._data)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         raise errorclass(errno, errval)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     pymysql.err.InternalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x88' for column '_description' at row 1")
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     The above exception was the direct cause of the following exception:
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     Traceback (most recent call last):
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/root/Forces/setup/xmlsetup.py", line 200, in create_boxes
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         dbsession.flush()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2459, in flush
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         self._flush(objects)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2597, in _flush
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         transaction.rollback(_capture_exception=True)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         compat.reraise(exc_type, exc_value, exc_tb)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         raise value
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2557, in _flush
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         flush_context.execute()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         rec.execute(self)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         uow,
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         insert,
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1138, in _emit_insert_statements
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         statement, params
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         return meth(self, multiparams, params)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         return connection._execute_clauseelement(self, multiparams, params)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         distilled_params,
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         e, statement, parameters, cursor, context
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         util.raise_from_cause(sqlalchemy_exception, exc_info)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         reraise(type(exception), exception, tb=exc_tb, cause=cause)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         raise value.with_traceback(tb)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         cursor, statement, parameters, context
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         cursor.execute(statement, parameters)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 170, in execute
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         result = self._query(query)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 328, in _query
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         conn.query(q)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 517, in query
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         self._affected_rows = self._read_query_result(unbuffered=unbuffered)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 732, in _read_query_result
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         result.read()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1075, in read
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         first_packet = self.connection._read_packet()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         packet.check_error()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         err.raise_mysql_exception(self._data)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         raise errorclass(errno, errval)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x88' for column '_description' at row 1")
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [SQL: INSERT INTO box (created, uuid, corporation_id, category_id, _name, _operating_system, _description, _capture_message, _difficulty, game_level_id, _avatar, _value, garbage, flag_submission_type) VALUES (%(created)s, %(uuid)s, %(corporation_id)s, %(category_id)s, %(_name)s, %(_operating_system)s, %(_description)s, %(_capture_message)s, %(_difficulty)s, %(game_level_id)s, %(_avatar)s, %(_value)s, %(garbage)s, %(flag_submission_type)s)]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [parameters: {'created': datetime.datetime(2019, 10, 26, 23, 58, 30, 996633), 'uuid': '49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139', 'corporation_id': 3, 'category_id': None, '_name': 'Encryption', '_operating_system': 'none', '_description': 'Go to the web page using the IP provided and start collecting your flags and decrypting it😈', '_capture_message': '', '_difficulty': 'Easy - Medium', 'game_level_id': 1, '_avatar': 'upload/49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139.jpeg', '_value': 5, 'garbage': 'c64923f9248e39264255988b39f7ce66', 'flag_submission_type': 'CLASSIC'}]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     (Background on this error at: http://sqlalche.me/e/2j85)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]: [E 191026 23:58:31 xmlsetup:223] Faild to create corporation #2 (This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.InternalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x88' for column '_description' at row 1")
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [SQL: INSERT INTO box (created, uuid, corporation_id, category_id, _name, _operating_system, _description, _capture_message, _difficulty, game_level_id, _avatar, _value, garbage, flag_submission_type) VALUES (%(created)s, %(uuid)s, %(corporation_id)s, %(category_id)s, %(_name)s, %(_operating_system)s, %(_description)s, %(_capture_message)s, %(_difficulty)s, %(game_level_id)s, %(_avatar)s, %(_value)s, %(garbage)s, %(flag_submission_type)s)]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [parameters: {'created': datetime.datetime(2019, 10, 26, 23, 58, 30, 996633), 'uuid': '49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139', 'corporation_id': 3, 'category_id': None, '_name': 'Encryption', '_operating_system': 'none', '_description': 'Go to the web page using the IP provided and start collecting your flags and decrypting it😈', '_capture_message': '', '_difficulty': 'Easy - Medium', 'game_level_id': 1, '_avatar': 'upload/49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139.jpeg', '_value': 5, 'garbage': 'c64923f9248e39264255988b39f7ce66', 'flag_submission_type': 'CLASSIC'}]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     (Background on this error at: http://sqlalche.me/e/2j85) (Background on this error at: http://sqlalche.me/e/7s2a))
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     Traceback (most recent call last):
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/root/Forces/setup/xmlsetup.py", line 216, in create_corps
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         if Corporation.by_name(corporation.name) is None:
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/root/Forces/models/Corporation.py", line 65, in by_name
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         return dbsession.query(cls).filter_by(_name=str(name)).first()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3232, in first
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         ret = list(self[0:1])
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3018, in __getitem__
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         return list(res)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         return self._execute_and_instances(context)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         querycontext, self._connection_from_session, close_with_result=True
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         mapper=self._bind_mapper(), clause=querycontext.statement, **kw
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         conn = self.session.connection(**kw)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1124, in connection
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         execution_options=execution_options,
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         engine, execution_options
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 408, in _connection_for_bind
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         self._assert_active()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         code="7s2a",
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.InternalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x88' for column '_description' at row 1")
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [SQL: INSERT INTO box (created, uuid, corporation_id, category_id, _name, _operating_system, _description, _capture_message, _difficulty, game_level_id, _avatar, _value, garbage, flag_submission_type) VALUES (%(created)s, %(uuid)s, %(corporation_id)s, %(category_id)s, %(_name)s, %(_operating_system)s, %(_description)s, %(_capture_message)s, %(_difficulty)s, %(game_level_id)s, %(_avatar)s, %(_value)s, %(garbage)s, %(flag_submission_type)s)]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [parameters: {'created': datetime.datetime(2019, 10, 26, 23, 58, 30, 996633), 'uuid': '49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139', 'corporation_id': 3, 'category_id': None, '_name': 'Encryption', '_operating_system': 'none', '_description': 'Go to the web page using the IP provided and start collecting your flags and decrypting it😈', '_capture_message': '', '_difficulty': 'Easy - Medium', 'game_level_id': 1, '_avatar': 'upload/49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139.jpeg', '_value': 5, 'garbage': 'c64923f9248e39264255988b39f7ce66', 'flag_submission_type': 'CLASSIC'}]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     (Background on this error at: http://sqlalche.me/e/2j85) (Background on this error at: http://sqlalche.me/e/7s2a)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]: [E 191026 23:58:31 xmlsetup:223] Faild to create corporation #3 (This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.InternalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x88' for column '_description' at row 1")
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [SQL: INSERT INTO box (created, uuid, corporation_id, category_id, _name, _operating_system, _description, _capture_message, _difficulty, game_level_id, _avatar, _value, garbage, flag_submission_type) VALUES (%(created)s, %(uuid)s, %(corporation_id)s, %(category_id)s, %(_name)s, %(_operating_system)s, %(_description)s, %(_capture_message)s, %(_difficulty)s, %(game_level_id)s, %(_avatar)s, %(_value)s, %(garbage)s, %(flag_submission_type)s)]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [parameters: {'created': datetime.datetime(2019, 10, 26, 23, 58, 30, 996633), 'uuid': '49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139', 'corporation_id': 3, 'category_id': None, '_name': 'Encryption', '_operating_system': 'none', '_description': 'Go to the web page using the IP provided and start collecting your flags and decrypting it😈', '_capture_message': '', '_difficulty': 'Easy - Medium', 'game_level_id': 1, '_avatar': 'upload/49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139.jpeg', '_value': 5, 'garbage': 'c64923f9248e39264255988b39f7ce66', 'flag_submission_type': 'CLASSIC'}]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     (Background on this error at: http://sqlalche.me/e/2j85) (Background on this error at: http://sqlalche.me/e/7s2a))
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     Traceback (most recent call last):
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/root/Forces/setup/xmlsetup.py", line 216, in create_corps
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         if Corporation.by_name(corporation.name) is None:
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/root/Forces/models/Corporation.py", line 65, in by_name
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         return dbsession.query(cls).filter_by(_name=str(name)).first()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3232, in first
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         ret = list(self[0:1])
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3018, in __getitem__
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         return list(res)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         return self._execute_and_instances(context)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         querycontext, self._connection_from_session, close_with_result=True
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         mapper=self._bind_mapper(), clause=querycontext.statement, **kw
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         conn = self.session.connection(**kw)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1124, in connection
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         execution_options=execution_options,
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         engine, execution_options
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 408, in _connection_for_bind
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         self._assert_active()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         code="7s2a",
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.InternalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x88' for column '_description' at row 1")
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [SQL: INSERT INTO box (created, uuid, corporation_id, category_id, _name, _operating_system, _description, _capture_message, _difficulty, game_level_id, _avatar, _value, garbage, flag_submission_type) VALUES (%(created)s, %(uuid)s, %(corporation_id)s, %(category_id)s, %(_name)s, %(_operating_system)s, %(_description)s, %(_capture_message)s, %(_difficulty)s, %(game_level_id)s, %(_avatar)s, %(_value)s, %(garbage)s, %(flag_submission_type)s)]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [parameters: {'created': datetime.datetime(2019, 10, 26, 23, 58, 30, 996633), 'uuid': '49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139', 'corporation_id': 3, 'category_id': None, '_name': 'Encryption', '_operating_system': 'none', '_description': 'Go to the web page using the IP provided and start collecting your flags and decrypting it😈', '_capture_message': '', '_difficulty': 'Easy - Medium', 'game_level_id': 1, '_avatar': 'upload/49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139.jpeg', '_value': 5, 'garbage': 'c64923f9248e39264255988b39f7ce66', 'flag_submission_type': 'CLASSIC'}]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     (Background on this error at: http://sqlalche.me/e/2j85) (Background on this error at: http://sqlalche.me/e/7s2a)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]: [E 191026 23:58:31 xmlsetup:244] Exception raised while parsing /tmp/tmpwxo3cx9c, rolling back changes
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     Traceback (most recent call last):
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/root/Forces/setup/xmlsetup.py", line 239, in _xml_file_import
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         dbsession.commit()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1027, in commit
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         self.transaction.commit()
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 492, in commit
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         self._assert_active(prepared_ok=True)
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:       File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:         code="7s2a",
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.InternalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x88' for column '_description' at row 1")
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [SQL: INSERT INTO box (created, uuid, corporation_id, category_id, _name, _operating_system, _description, _capture_message, _difficulty, game_level_id, _avatar, _value, garbage, flag_submission_type) VALUES (%(created)s, %(uuid)s, %(corporation_id)s, %(category_id)s, %(_name)s, %(_operating_system)s, %(_description)s, %(_capture_message)s, %(_difficulty)s, %(game_level_id)s, %(_avatar)s, %(_value)s, %(garbage)s, %(flag_submission_type)s)]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     [parameters: {'created': datetime.datetime(2019, 10, 26, 23, 58, 30, 996633), 'uuid': '49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139', 'corporation_id': 3, 'category_id': None, '_name': 'Encryption', '_operating_system': 'none', '_description': 'Go to the web page using the IP provided and start collecting your flags and decrypting it😈', '_capture_message': '', '_difficulty': 'Easy - Medium', 'game_level_id': 1, '_avatar': 'upload/49fcdbe8-7d8b-47e9-9c2f-31ae5f54f139.jpeg', '_value': 5, 'garbage': 'c64923f9248e39264255988b39f7ce66', 'flag_submission_type': 'CLASSIC'}]
Oct 26 23:58:31 CyberAgora-Droplet python3.6[11806]:     (Background on this error at: http://sqlalche.me/e/2j85) (Background on this error at: http://sqlalche.me/e/7s2a)

```

**Comment by jeffg2k** [comment]
The issue is that it doesn't like the 😈emoji in the description.  I'll review the code and see if we can get it to handle that.

**Comment by CovertError** [comment]
yea thought so

**Comment by jeffg2k** [comment]
I've been unable to reproduce this thus far using your dataset.  I updated the box to include the emjoi in the description.  I was then able to export and import with the emoji with no errors.  I see posts online that describe the issue, but it's usually a mysql utf8 issue with things not being set to utf8mb4.  However, based on your export, it looks like utf8mb4, which is what we define in the RTB connection string.  So, not sure... 

Just to clarify, you're able to edit your description without issue.  Export to XML without issue.  It only gives you an issue on Import?  It's one of those things that it should either not work or work.  If it can save it to the database and export it.  It shouldn't have an issue resaving it via import.

**Comment by CovertError** [comment]
this issue doesn't seem to exist any more thanks @jeffg2k
