### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#299]
This issue happened after the latest update I think this only happens with the admin user not sure tho
```
Oct 27 22:54:07 rtb-Droplet python3.6[24041]: [I 191027 22:54:07 PublicHandlers:114] Successful login: admin from 83.110.104.92
Oct 27 22:54:07 rtb-Droplet python3.6[24041]: [I 191027 22:54:07 web:2246] 302 POST /login (83.110.104.92) 339.80ms
Oct 27 22:54:07 rtb-Droplet python3.6[24041]: [E 191027 22:54:07 web:1788] Uncaught exception GET /user (83.110.104.92)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     HTTPServerRequest(protocol='https', host='rtb.tech:8888', method='GET', uri='/user', version='HTTP/1.1', remote_ip='83.110.104.92')
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     Traceback (most recent call last):
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         result = method(*self.path_args, **self.path_kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/libs/SecurityDecorators.py", line 46, in wrapper
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return method(self, *args, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/handlers/UserHandlers.py", line 54, in get
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         self.render("admin/home.html", user=user)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         html = self.render_string(template_name, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return t.generate(**namespace)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return execute()
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "admin/home_html.generated.py", line 84, in _tt_execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         _tt_tmp = _tt_modules.Menu()  # main.html:30
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         rendered = self._active_modules[name].render(*args, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/modules/Menu.py", line 49, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         scoreboard_visible=scoreboard_visible,
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return self.handler.render_string(path, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return t.generate(**namespace)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return execute()
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "menu/admin_html.generated.py", line 147, in _tt_execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         if user.theme == 'Cyborg' or user.theme == 'Slate':  # menu/admin.html:150
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     NameError: name 'user' is not defined
Oct 27 22:54:07 rtb-Droplet python3.6[24041]: [E 191027 22:54:07 BaseHandlers:196] Request from 83.110.104.92 resulted in an error code 500:
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     Traceback (most recent call last):
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         result = method(*self.path_args, **self.path_kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/libs/SecurityDecorators.py", line 46, in wrapper
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return method(self, *args, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/handlers/UserHandlers.py", line 54, in get
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         self.render("admin/home.html", user=user)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         html = self.render_string(template_name, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return t.generate(**namespace)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return execute()
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "admin/home_html.generated.py", line 84, in _tt_execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         _tt_tmp = _tt_modules.Menu()  # main.html:30
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         rendered = self._active_modules[name].render(*args, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/modules/Menu.py", line 49, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         scoreboard_visible=scoreboard_visible,
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return self.handler.render_string(path, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return t.generate(**namespace)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return execute()
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "menu/admin_html.generated.py", line 147, in _tt_execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         if user.theme == 'Cyborg' or user.theme == 'Slate':  # menu/admin.html:150
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     NameError: name 'user' is not defined
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:
Oct 27 22:54:07 rtb-Droplet python3.6[24041]: [E 191027 22:54:07 web:1216] Uncaught exception in write_error
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     Traceback (most recent call last):
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         result = method(*self.path_args, **self.path_kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/libs/SecurityDecorators.py", line 46, in wrapper
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return method(self, *args, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/handlers/UserHandlers.py", line 54, in get
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         self.render("admin/home.html", user=user)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         html = self.render_string(template_name, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return t.generate(**namespace)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return execute()
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "admin/home_html.generated.py", line 84, in _tt_execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         _tt_tmp = _tt_modules.Menu()  # main.html:30
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         rendered = self._active_modules[name].render(*args, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/modules/Menu.py", line 49, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         scoreboard_visible=scoreboard_visible,
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return self.handler.render_string(path, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return t.generate(**namespace)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return execute()
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "menu/admin_html.generated.py", line 147, in _tt_execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         if user.theme == 'Cyborg' or user.theme == 'Slate':  # menu/admin.html:150
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     NameError: name 'user' is not defined
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     During handling of the above exception, another exception occurred:
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     Traceback (most recent call last):
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1214, in send_error
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         self.write_error(status_code, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/handlers/BaseHandlers.py", line 206, in write_error
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         self.render("public/404.html")
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         html = self.render_string(template_name, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return t.generate(**namespace)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return execute()
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "public/404_html.generated.py", line 14, in _tt_execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         _tt_tmp = _tt_modules.Menu()  # main.html:30
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         rendered = self._active_modules[name].render(*args, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/root/rtb/modules/Menu.py", line 49, in render
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         scoreboard_visible=scoreboard_visible,
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return self.handler.render_string(path, **kwargs)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return t.generate(**namespace)
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         return execute()
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:       File "menu/admin_html.generated.py", line 147, in _tt_execute
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:         if user.theme == 'Cyborg' or user.theme == 'Slate':  # menu/admin.html:150
Oct 27 22:54:07 rtb-Droplet python3.6[24041]:     NameError: name 'user' is not defined
Oct 27 22:54:07 rtb-Droplet python3.6[24041]: [E 191027 22:54:07 web:2246] 500 GET /user (83.110.104.92) 78.73ms
```

**Comment by jeffg2k** [comment]
Thanks - tested it with a non-admin account, but not the admin.  I assumed they both had the user variable.  Apparently not - oops.  Now they're identical in the variables passed.
