### ISSUE TITLE
Theme Problem

### ISSUE THREAD

**Issue by CovertError** [moloch--/RootTheBox#300]
I'm using the journal theme and for some reason, it keeps going back to the default theme this is what I found in the logs I don't think it helps much but do let me know what I can do to better debug it?
```
Oct 23 22:02:39 rtb-Droplet python3.6[3306]: [E 191023 22:02:39 Theme:122] Problem with theme - reloading...
Oct 23 22:02:39 rtb-Droplet python3.6[3306]: [E 191023 22:02:39 Theme:130] Error with theme relationship. Returning default Cyborg theme
Oct 23 22:02:39 rtb-Droplet python3.6[3306]: [I 191023 22:02:39 web:2246] 200 GET /user (83.110.15.185) 421.20ms
Oct 23 22:02:40 rtb-Droplet python3.6[3306]: [I 191023 22:02:40 web:2246] 200 GET /static/css/pages/admin/home.css (83.110.15.185) 5.08ms
Oct 23 22:02:40 rtb-Droplet python3.6[3306]: [I 191023 22:02:40 web:2246] 200 GET /static/js/pages/admin/home.js (83.110.15.185) 1.28ms
Oct 23 22:02:40 rtb-Droplet python3.6[3306]: [I 191023 22:02:40 web:2246] 200 GET /static/images/info.png (83.110.15.185) 2.59ms
Oct 23 22:02:40 rtb-Droplet python3.6[3306]: [I 191023 22:02:40 web:2246] 200 GET /scoreboard/ajax/timer (83.110.15.185) 1.11ms
Oct 23 22:02:40 rtb-Droplet python3.6[3306]: [I 191023 22:02:40 web:2246] 200 GET /admin/gitstatus (83.110.15.185) 97.97ms
Oct 23 22:02:40 rtb-Droplet python3.6[3306]: [I 191023 22:02:40 web:2246] 200 GET /static/images/success.png (83.110.15.185) 7.22ms
Oct 23 22:02:40 rtb-Droplet python3.6[3306]: [I 191023 22:02:40 web:2246] 200 GET /static/images/warning.png (83.110.15.185) 1.06ms
Oct 23 22:02:40 rtb-Droplet python3.6[3306]: [I 191023 22:02:40 web:2246] 101 GET /connect/notifications/updates (83.110.15.185) 1.97ms
Oct 23 22:02:40 rtb-Droplet python3.6[3306]: [I 191023 22:02:40 web:2246] 200 GET /static/css/themes/cyborg.min.css (83.110.15.185) 655.89ms
Oct 23 22:02:41 rtb-Droplet python3.6[3306]: [I 191023 22:02:41 web:2246] 200 GET /static/css/droidsans.css (83.110.15.185) 1.37ms
Oct 23 22:02:41 rtb-Droplet python3.6[3306]: [I 191023 22:02:41 web:2246] 200 GET /static/font/droidsans.woff (83.110.15.185) 1.34ms
Oct 23 22:02:41 rtb-Droplet python3.6[3306]: [I 191023 22:02:41 web:2246] 200 GET /static/font/droidsans-bold.woff (83.110.15.185) 1.08ms
Oct 23 22:02:45 rtb-Droplet python3.6[3306]: [E 191023 22:02:45 Theme:122] Problem with theme - reloading...
Oct 23 22:02:45 rtb-Droplet python3.6[3306]: [E 191023 22:02:45 Theme:130] Error with theme relationship. Returning default Cyborg theme
```

**Comment by jeffg2k** [comment]
I've pushed a change to try and fix this.  I think it might be when the session expires, so it's difficult to reproduce.  Let me know if you continue to have the issue or not.

**Comment by jeffg2k** [comment]
Some additional information - I added a tweak https://github.com/moloch--/RootTheBox/commit/5fcd08d3a8710073924f791076c8a19cb2cb5455 to try to load the relationship without "lazy".  Not sure if that will fix it or not.

```
    Traceback (most recent call last):
      File "/home/ctf/RootTheBox/models/Theme.py", line 112, in __iter__
        for _file in self.files:
      File "/home/ctf/.local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "/home/ctf/.local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 710, in get
        value = self.callable_(state, passive)
      File "/home/ctf/.local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 693, in _load_for_state
        % (orm_util.state_str(state), self.key)
    sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Theme at 0x7f2c4864a898> is not bound to a Session; lazy load operation of attribute 'files' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/ctf/RootTheBox/handlers/PublicHandlers.py", line 63, in get
        self.render("public/login.html", info=None, errors=None)
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
        return execute()
      File "public/login_html.generated.py", line 13, in _tt_execute
        _tt_tmp = _tt_modules.Theme()  # main.html:26
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
        rendered = self._active_modules[name].render(*args, **kwargs)
      File "/home/ctf/RootTheBox/modules/AppTheme.py", line 44, in render
        return self.render_string("theme/theme.html", theme_files=self.theme)
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
        return self.handler.render_string(path, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
        return execute()
      File "theme/theme_html.generated.py", line 4, in _tt_execute
        for resource in theme_files:  # theme/theme.html:1
      File "/home/ctf/RootTheBox/models/Theme.py", line 116, in __iter__
        if self.name == "386":
      File "/home/ctf/RootTheBox/models/Theme.py", line 104, in name
        return self._name
      File "/home/ctf/.local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "/home/ctf/.local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 705, in get
        value = state._load_expired(state, passive)
      File "/home/ctf/.local/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
        self.manager.deferred_scalar_loader(self, toload)
      File "/home/ctf/.local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 913, in load_scalar_attributes
        "attribute refresh operation cannot proceed" % (state_str(state))
    sqlalchemy.orm.exc.DetachedInstanceError: Instance <Theme at 0x7f2c4864a898> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
```

**Comment by jeffg2k** [comment]
This still happens after the session expires...

**Comment by jeffg2k** [comment]
I'm testing out adding `expire_on_commit=False` to the db session creation.  It should fix it but I'm not sure what the negative side effects could be.

**Comment by jeffg2k** [comment]
Think I finally got this one fixed with https://github.com/moloch--/RootTheBox/commit/1b0405935ba35eaead0b5fe60a4928481539f2ba
