### ISSUE TITLE
Scoreboard not showing list players and their scores and captured flags

### ISSUE THREAD

**Issue by jhibaler** [moloch--/RootTheBox#312]
Hello, I think there's a bug currently in the scoreboard page as I am seeing the following error in the journalctl logs:

```
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:     HTTPServerRequest(protocol='http', host='165.22.58.119:1127', method='GET', uri='/scoreboard/ajax/summary', version='HTTP/1.1', remote_ip='130.105.243.101')
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:     Traceback (most recent call last):
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         result = method(*self.path_args, **self.path_kwargs)
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/opt/CTF/RootTheBox/handlers/ScoreboardHandlers.py", line 104, in get
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         uri[args[0]]()
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/opt/CTF/RootTheBox/handlers/ScoreboardHandlers.py", line 128, in summary_table
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         game_state=self.settings["scoreboard_state"],
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         html = self.render_string(template_name, **kwargs)
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         return t.generate(**namespace)
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         return execute()
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "scoreboard/summary_table_html.generated.py", line 98, in _tt_execute
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         _tt_tmp = level.name  # scoreboard/summary_table.html:48
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:     AttributeError: 'dict' object has no attribute 'name'
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]: [E 191128 20:03:26 BaseHandlers:197] Request from 130.105.243.101 resulted in an error code 500:
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:     Traceback (most recent call last):
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         result = method(*self.path_args, **self.path_kwargs)
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/opt/CTF/RootTheBox/handlers/ScoreboardHandlers.py", line 104, in get
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         uri[args[0]]()
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/opt/CTF/RootTheBox/handlers/ScoreboardHandlers.py", line 128, in summary_table
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         game_state=self.settings["scoreboard_state"],
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         html = self.render_string(template_name, **kwargs)
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         return t.generate(**namespace)
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         return execute()
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:       File "scoreboard/summary_table_html.generated.py", line 98, in _tt_execute
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:         _tt_tmp = level.name  # scoreboard/summary_table.html:48
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:     AttributeError: 'dict' object has no attribute 'name'
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]:
Nov 28 20:03:26 rtb-msoc rootthebox.py[30787]: [E 191128 20:03:26 web:2246] 500 GET /scoreboard/ajax/summary (130.105.243.101) 16.17ms
```

**Comment by jeffg2k** [comment]
Thanks for the report - fixed
