### ISSUE TITLE
Error 500 GET /scoreboard/ajax/summary

### ISSUE THREAD

**Issue by loi219** [moloch--/RootTheBox#320]
Thanks for your application, it's really intuitive and give me all the functions I could imagine.
But when i'm trying to use the websocket, I've got an error  `500 GET /scoreboard/ajax/summary (x.x.x.x) 40.41ms`

Here's the stack trace from the server logs
```
[E 191208 10:54:59 BaseHandlers:197] Request from x.x.x.x resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/CTF/RootTheBox/handlers/ScoreboardHandlers.py", line 104, in get
        uri[args[0]]()
      File "/opt/CTF/RootTheBox/handlers/ScoreboardHandlers.py", line 128, in summary_table
        game_state=self.settings["scoreboard_state"],
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
        return execute()
      File "scoreboard/summary_table_html.generated.py", line 187, in _tt_execute
        for index, flag in enumerate(box.flags):  # scoreboard/summary_table.html:77
    AttributeError: 'dict' object has no attribute 'flags'

```
I've tried to deactivate the TLS but nothing change

**Comment by loi219** [comment]
Here's the versions:

> Root the Box v3.3.1
>  SQL Alchemy v1.3.11
>      Torando v6.0.3

**Comment by jeffg2k** [comment]
Pushed a fix for this issue - thanks for the report and stack trace!
