### ISSUE TITLE
 Request to update the database

### ISSUE THREAD

**Issue by cohux** [moloch--/RootTheBox#324]
update 323，enable Open source market and black market, users log in http 500

errerinfo:
    ValueError: Item 'Source Code Market' not in database.

**Comment by jeffg2k** [comment]
Can you provide a stack trace (debug) for this error?  I'm not sure how to reproduce it.  I haven't been able to do so.

**Comment by cohux** [comment]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/opt/RootTheBox/handlers/UserHandlers.py", line 62, in get
    self.render("user/home.html", user=user, game_started=game_started)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
    return execute()
  File "user/home_html.generated.py", line 26, in _tt_execute
    _tt_tmp = _tt_modules.Menu()  # main.html:30
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
    rendered = self._active_modules[name].render(*args, **kwargs)
  File "/opt/RootTheBox/modules/Menu.py", line 43, in render
    "menu/user.html", user=user, scoreboard_visible=scoreboard_visible
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
    return self.handler.render_string(path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
    return execute()
  File "menu/user_html.generated.py", line 149, in _tt_execute
    if user.has_item("Source Code Market"):  # menu/user.html:116
  File "/opt/RootTheBox/models/User.py", line 313, in has_item
    raise ValueError("Item '%s' not in database." % str(item_name))
ValueError: Item 'Source Code Market' not in database.`

**Comment by cohux** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/opt/RootTheBox/handlers/UserHandlers.py", line 62, in get
    self.render("user/home.html", user=user, game_started=game_started)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 856, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
    return execute()
  File "user/home_html.generated.py", line 26, in _tt_execute
    _tt_tmp = _tt_modules.Menu()  # main.html:30
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1797, in render
    rendered = self._active_modules[name].render(*args, **kwargs)
  File "/opt/RootTheBox/modules/Menu.py", line 43, in render
    "menu/user.html", user=user, scoreboard_visible=scoreboard_visible
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3243, in render_string
    return self.handler.render_string(path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1005, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python3.6/dist-packages/tornado/template.py", line 361, in generate
    return execute()
  File "menu/user_html.generated.py", line 149, in _tt_execute
    if user.has_item("Source Code Market"):  # menu/user.html:116
  File "/opt/RootTheBox/models/User.py", line 313, in has_item
    raise ValueError("Item '%s' not in database." % str(item_name))
ValueError: Item 'Source Code Market' not in database.
```

**Comment by cohux** [comment]
> Can you provide a stack trace (debug) for this error? I'm not sure how to reproduce it. I haven't been able to do so.

**Comment by jeffg2k** [comment]
I'm not sure why that would not be in the database as that table is setup by default.  You could try to run `SELECT * FROM market_item;` in your database to see what comes up.  

The check that is failing suggests you don't have an entry with the name `Source Code Market` in the `market_item` table.
