### ISSUE TITLE
Some commands fail in the recovery console

### ISSUE THREAD

**Issue by noraj** [moloch--/RootTheBox#332]
Some commands fail in the recovery console: ls

```
Recovery > ls                                                                                                                                                                                   
[*] admin (admin)                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                              
  File "./rootthebox.py", line 855, in <module>                                                                                                                                                 
    recovery()                                                                                                                                                                                  
  File "./rootthebox.py", line 123, in recovery                                                                                                                                                 
    console.cmdloop()                                                                                                                                                                           
  File "/usr/local/lib/python3.8/cmd.py", line 138, in cmdloop                                                                                                                                  
    stop = self.onecmd(line)                                                                                                                                                                    
  File "/usr/local/lib/python3.8/cmd.py", line 217, in onecmd                                                                                                                                   
    return func(arg)                                                                                                                                                                            
  File "/opt/rtb/setup/recovery.py", line 81, in do_ls                                                                                                                                          
    team = " from " + bold + str(user.team) + W + " "                                                                                                                                           
TypeError: __str__ returned non-string (type bytes)                                                                                                                                             

Recovery > ls user
[*] admin (admin)
Traceback (most recent call last):
  File "./rootthebox.py", line 855, in <module>
    recovery()
  File "./rootthebox.py", line 123, in recovery
    console.cmdloop()
  File "/usr/local/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/opt/rtb/setup/recovery.py", line 81, in do_ls
    team = " from " + bold + str(user.team) + W + " "
TypeError: __str__ returned non-string (type bytes)

Recovery > ls team
[*] noraj: noraj
[*] noraj2: noraj2
[*] noraj3: noraj3
```

It's weird because team are disabled and only user are enabled.

![image](https://user-images.githubusercontent.com/16578570/72527948-32e86000-386a-11ea-9ee0-11b8bb2662b4.png)

So it seems that user and team are inverted and that if team are disabled then trying to ls team (actual under suer) fails instead of saying disabled.

**Comment by noraj** [comment]
I see technically individual competition is made of team of one people.
