### ISSUE TITLE
Box Garbage Files

### ISSUE THREAD

**Issue by nunoguerreiro** [moloch--/RootTheBox#348]
Hi guys, first would like to understand what is the functionality about garbaging a box ?

There is an error when we try to garbage a box. See error below:

[E 200229 15:54:55 web:1788] Uncaught exception GET /admin/garbage?uuid=970764d5-867a-4a47-9dd8-c932ea313ca5 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/admin/garbage?uuid=970764d5-867a-4a47-9dd8-c932ea313ca5', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/nmag/.local/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/nmag/Desktop/CTFs/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
        return method(self, *args, **kwargs)
      File "/home/nmag/Desktop/CTFs/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
        return method(self, *args, **kwargs)
      File "/home/nmag/Desktop/CTFs/RootTheBox/libs/SecurityDecorators.py", line 108, in wrapper
        return method(self, *args, **kwargs)
      File "/home/nmag/Desktop/CTFs/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 400, in get
        data = box.get_garbage_cfg()
      File "/home/nmag/Desktop/CTFs/RootTheBox/models/Box.py", line 299, in get_garbage_cfg
        encode(self.name, "hex"),
      File "/home/nmag/Desktop/CTFs/RootTheBox/libs/StringCoding.py", line 38, in encode
        rv, length = codec.encode(s, *args, **kwargs)
      File "/usr/lib/python3.6/encodings/hex_codec.py", line 15, in hex_encode
        return (binascii.b2a_hex(input), len(input))
    TypeError: a bytes-like object is required, not 'str'
[E 200229 15:54:55 BaseHandlers:199] Request from 127.0.0.1 resulted in an error code 500:
    Traceback (most recent call last):
      File "/home/nmag/.local/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/nmag/Desktop/CTFs/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
        return method(self, *args, **kwargs)
      File "/home/nmag/Desktop/CTFs/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
        return method(self, *args, **kwargs)
      File "/home/nmag/Desktop/CTFs/RootTheBox/libs/SecurityDecorators.py", line 108, in wrapper
        return method(self, *args, **kwargs)
      File "/home/nmag/Desktop/CTFs/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 400, in get
        data = box.get_garbage_cfg()
      File "/home/nmag/Desktop/CTFs/RootTheBox/models/Box.py", line 299, in get_garbage_cfg
        encode(self.name, "hex"),
      File "/home/nmag/Desktop/CTFs/RootTheBox/libs/StringCoding.py", line 38, in encode
        rv, length = codec.encode(s, *args, **kwargs)
      File "/usr/lib/python3.6/encodings/hex_codec.py", line 15, in hex_encode
        return (binascii.b2a_hex(input), len(input))
    TypeError: a bytes-like object is required, not 'str'
    
[E 200229 15:54:55 web:2246] 500 GET /admin/garbage?uuid=970764d5-867a-4a47-9dd8-c932ea313ca5 (127.0.0.1) 28.57ms
[I 200229 15:54:55 web:2246] 101 GET /connect/notifications/updates (127.0.0.1) 1.07ms

**Comment by jeffg2k** [comment]
The garbage file is used for bots. It is generated by the administrator in scoring engine. When you create a box, you should be able to download a copy and upload it to the target server(s). This file basically contains some random data which is part of a zero-knowledge proof that confirms the bot has access to the target machines and not running on a box outside the scope of the game.

As for the error, thanks for the report - I'm going to push a fix now.  Updating a Python 2 application for Python 3 compatibility is a pain and we're still finding little issues like this.  I've also made the Garbage File download only visible on the management page if you have Bots enabled and I clarified that it is for the "Bot".
