### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by moloch--** [moloch--/RootTheBox#35]
Work in progress https://github.com/moloch--/RootTheBox/tree/py3

**Comment by RyPeck** [comment]
Do you aim to have this be compatible with Python 2 and 3?

**Comment by moloch--** [comment]
I looked into Python 3 compatibility and it is slated for future improvements. However, due to the major changes in `urlparse` and related libraries compatibility with both 2 and 3 is tricky.

**Comment by noraj1337** [comment]
A python 3 issue https://github.com/moloch--/RootTheBox/issues/120

**Comment by noraj1337** [comment]
PR https://github.com/moloch--/RootTheBox/pull/131 is about adding python 3 support for the actual code (master tree) so it's supports both python 2 and 3.

**Comment by noraj1337** [comment]
Since python 3.6, hashlib contains support for BLAKE2/SHA3. https://fossies.org/diffs/Python/3.5.2_vs_3.6.0/Doc/library/hashlib.rst-diff.html

This will allow the support of new algorithms for user passwords.

**Comment by jeffg2k** [comment]
I've started a new branch to support Python 3.  https://github.com/jeffg2k/RootTheBox/tree/Python3
I quickly tested the basic pages, box / flag creation, submission and things seem to be working in both Python 2.7 & 3.6.  But due to the various compatibility challenges in Python 3, like their changes to str / unicode / bytes, I figured it best to create a new branch that perhaps gets additional testing.   I expect to make a pull request shortly for RTB v2.0 and @moloch-- can decide if he wants that to include the Python 3 branch changes.  Bite the bullet or do it in stages.. haha

**Comment by jeffg2k** [comment]
I've pushed a new branch to bring Python3 support to RTB.  It needs some further testing on both Python 2.7 and Python 3.x to make sure everything works using either version.  If anyone has some time, it would be really helpful.

Going to tag some users that have been active in reporting and working through RTB issues recently: @stealthsploit @mohammadHmedat @Xlaits @garanews

**Comment by Xlaits** [comment]
Thank you for the tag. I'll be in the lab Thursday and Friday. I'll have to
check it out then.

**Comment by garanews** [comment]
Hello, thanks.
Just cloned the python3 branch. Installed the new python3 deps running setup/python3-depends.sh
Then copied old config file and started.
![image](https://user-images.githubusercontent.com/16938405/53476559-f30e6380-3a72-11e9-84e4-27a43ab685f8.png)
I'm playng around pages and just received this message:
```
[E 190227 03:37:03 ioloop:801] Exception in callback <bound method GameHistory.take_snapshot of <libs.GameHistory.GameHistory object at 0x7f431d4ee588>>
    Traceback (most recent call last):
      File "/home/osboxes/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 1229, in _run
        return self.callback()
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/libs/GameHistory.py", line 78, in take_snapshot
        snapshot = self.__now__()
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/libs/GameHistory.py", line 124, in __now__
        snapshot_team.game_levels = team.game_levels
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/attributes.py", line 261, in __set__
        instance_state(instance), instance_dict(instance), value, None
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/attributes.py", line 1240, in set
        new_values, old_collection, new_collection, initiator=evt
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/collections.py", line 782, in bulk_replace
        constants = existing_idset.intersection(values or ())
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/_collections.py", line 610, in intersection
        result._members.update(self._working_set(members).intersection(other))
    TypeError: unhashable type: 'GameLevel'
```

 trying to update conf from gui I receive:
```
[I 190227 03:41:33 web:2162] 101 GET /connect/notifications/updates (192.168.111.1) 0.98ms
[E 190227 03:41:40 web:1670] Uncaught exception POST /admin/configuration (192.168.111.1)
    HTTPServerRequest(protocol='http', host='192.168.111.135:8888', method='POST', uri='/admin/configuration', version='HTTP/1.1', remote_ip='192.168.111.1')
    Traceback (most recent call last):
      File "/home/osboxes/.local/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/libs/SecurityDecorators.py", line 63, in wrapper
        return method(self, *args, **kwargs)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/libs/SecurityDecorators.py", line 38, in wrapper
        return method(self, *args, **kwargs)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/libs/SecurityDecorators.py", line 93, in wrapper
        return method(self, *args, **kwargs)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 344, in post
        self.config.restrict_registration = self.get_bool('restrict_registration', False)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 322, in get_bool
        if not isinstance(default, basestring):
    NameError: name 'basestring' is not defined
[E 190227 03:41:40 BaseHandlers:198] Request from 192.168.111.1 resulted in an error code 500:
    Traceback (most recent call last):
      File "/home/osboxes/.local/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/libs/SecurityDecorators.py", line 63, in wrapper
        return method(self, *args, **kwargs)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/libs/SecurityDecorators.py", line 38, in wrapper
        return method(self, *args, **kwargs)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/libs/SecurityDecorators.py", line 93, in wrapper
        return method(self, *args, **kwargs)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 344, in post
        self.config.restrict_registration = self.get_bool('restrict_registration', False)
      File "/home/osboxes/Desktop/RootTheBox3/RootTheBox/handlers/AdminHandlers/AdminGameHandlers.py", line 322, in get_bool
        if not isinstance(default, basestring):
    NameError: name 'basestring' is not defined

[E 190227 03:41:40 web:2162] 500 POST /admin/configuration (192.168.111.1) 34.09ms

```

**Comment by jeffg2k** [comment]
Thanks, i’ll fix the last error shortly.  The prior one I’ve seen and I'll try to figure out - snapshots are a @moloch-- magic box.

**Comment by jeffg2k** [comment]
@shshzi can you take a look at https://github.com/moloch--/RootTheBox/commit/b6ecf6bde35536c1dc3e6286e37e75680dee0da5
I'm not sure exactly what the "str" did in the class constructor, but it was causing issues with the Python3 conversion.  For now, I just removed it, but not sure if that will break it.  Please advise - thanks.

**Comment by moloch--** [comment]
* The `basestring`s should be easy to avoid, just replace with `isinstance` of `str`
* Looks like we need to implement a `__hash__()` method for `GameLevel`

**Comment by jeffg2k** [comment]
Python 3 branch merged.  RTB should now be Python 2.7.x & Python 3 compatible.  Let us know if you have any issues so we can quickly fix them.

**Comment by mohammadHmedat** [comment]
I will do my best to have a free time and testing, thanks

**Comment by jeffg2k** [comment]
PyPy compatibility also needs testing if anyone uses that.

**Comment by garanews** [comment]
I'm trying with pypy3.6-7 and when upload a file under team file share I am getting this error:
```
pypy3.6-7.2.0-linux_x86_64-portable/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/home/RootTheBox/handlers/FileUploadHandlers.py", line 63, in post
    file_upload = self.create_file(user, shared_file)
  File "/home/RootTheBox/handlers/FileUploadHandlers.py", line 89, in create_file
    file_upload.data = shared_file["body"]
  File "/home/RootTheBox/models/FileUpload.py", line 110, in data
    fp.write(encode(value, "base64"))
TypeError: a bytes-like object is required, not str
```
