### ISSUE TITLE
BotMonitor.py

### ISSUE THREAD

**Issue by nunoguerreiro** [moloch--/RootTheBox#350]
My discoveries:

1. to use the BotMonitor.py, you need to run it from the RTF root folder (due to some python dependencies from the internal libs folder:
2. Every time I try the BotMonitor.py, the bot will ask for a user/password (think that this is a valid user/pass player)
3. after putting the right user/pass combination, the bot exits with an exception - the log is below:

[INFO] 2020-02-29 15:40:21,440 - Connecting to ws://localhost:8888/botnet/climon
itor
[ERROR] 2020-02-29 15:40:53,840 - [WebSocket] on_error - <class 'TypeError'>
Traceback (most recent call last):
  File "./botnet_monitor_new.py", line 849, in run_forever
    self.sock.connect(self.url, header=self.header)
  File "./botnet_monitor_new.py", line 498, in connect
    self._handshake(hostname, port, resource, **options)
  File "./botnet_monitor_new.py", line 527, in _handshake
    sock.send(header_str)
**TypeError: a bytes-like object is required, not 'str'**
[INFO] 2020-02-29 15:40:53,841 - Waiting for animation thread to exit ...
[INFO] 2020-02-29 15:40:54,092 - All threads have joined
[DEBUG] 2020-02-29 15:40:54,092 - Stopping curses ui: None

Any ideas ?

**Comment by jeffg2k** [comment]
My experience with the Botnet feature is limited (Moloch developed that piece), but in my testing, I don't recall running `BotMonitor.py` as a separate process.  It should be integrated with RootTheBox interface.  If your logged in as administrator, it's under the Tools & Upgrades menu, there is an page for Botnet Monitor.   If your logged in as a user, then it's under the Game menu, Botnet, Command & Control, along with the options to download the bots.

After going that route, let me know if you see any issues.  I'm going to release a bug fix for the Bot Handler and an update for the Bot itself to make it more py2/py3 compatible.

**Comment by nunoguerreiro** [comment]
> ter going that route, let me know if you see any iss

yes. but not clear what is the syntax to run the bot client (bot.py) on the target machine...? ??

like :?
./bot.py --user player01 --garbage /tmp/player01 --secure --verbose --domain localhost --port 8888

**Comment by jeffg2k** [comment]
This is what I used to run it.
`python3 bot.py --garbage ~/Downloads/Box1.garbage --user eljeffe --domain 127.0.0.1 --port 8888`

**Comment by jeffg2k** [comment]
This is where that Garbage file comes in.  The bot has to point to the file, which the admin places on the target server.  Also, you may need to set the option `whitelist_box_ips = False` in your config unless you have the IP defined in the box.

**Comment by nunoguerreiro** [comment]
@jeffg2k the bot.py is working. BotMonitor.py (inside the bot folder not working)...

need just to understand the purpose... this bot is something that the "player" needs to start in the target machine (based on the garbage file that the admin places on the target server)...

Thanks a lot.

**Comment by jeffg2k** [comment]
I guess let me explain the process of running the botnet service and you can elaborate on which piece is giving you an issue.

### Administration
1. Start RootTheBox `$ python3 ./rootthebox.py --start`
2. Enable the Botnet via the the admin Configuration page (very bottom) `Botnets Enabled`.  Alternatively, set the `rootthebox.cfg` option `use_bots = True`  This makes the bot options and menu items visible to the admin and player.
3. Under Game Management, a button will now be visible for each box that says `NameOfBox Bot Garbage File`.  Download this Garbage File and put it on the target box (the machine the player needs to own and run the bot from).  This file basically contains some random data which is part of a zero-knowledge proof that confirms the bot has access to the target machines and not running on a box outside the scope of the game.
4. For the box, add the IP Address of the target machine.  This will whitelist the IP for that bot.  Alternatively, set the `whitelist_box_ips = False` if you want to allow it from any IP (also useful for testing if you want to run the bot from anywhere, such as localhost).
5. As administrator, you can view the Botnet progress under the Tools & Upgrades menu, there is an page for `Botnet Monitor`.

### Gameplay
1. Once Botnets are enabled, a menu option will become visible to players.  It's under the Game menu -> Botnet.  From here, they can view the Command & Control (aka Botnet Monitor) page.  There will also be a download option for the bot (downloads as `rtb_bot.py`; _a copy of bot.py_).
2. The player owns the target box as their CTF challenge, finds the `NameOfBox.garbage` file, and uploads the `rtb_bot.py`.
3. The player runs the `rtb_bot.py` from the target box using the garbage file.
    `$ python3 rtb_bot.py --garbage ./NameOfBox.garbage --user eljeffe --domain 192.20.0.1 --port 8888`
4. Bot connects and generates periodic points for the player.  The points and the bots can be seen on the Command & Control aka Botnet Monitor page.
