### ISSUE TITLE
Single box flag submissions cause a glitch in the matrix

### ISSUE THREAD

**Issue by rstocks** [moloch--/RootTheBox#407]
When a box is configured as a "single box" submission type, any submission for that box (correct or incorrect, doesn't matter) causes a glitch in the matrix. Note that while the browser is showing the 404 error page, the server is actually reporting a 500.

Log data:

```
Oct  4 09:16:38 devel rootthebox.py[1350]: [E 201004 09:16:38 web:1788] Uncaught exception POST /user/missions/boxes?uuid=c0df1486-d535-4ba4-82fe-42f1952786a4 (172.16.1.13)
Oct  4 09:16:38 devel rootthebox.py[1350]:     HTTPServerRequest(protocol='http', host='172.16.1.23:8888', method='POST', uri='/user/missions/boxes?uuid=c0df1486-d535-4ba4-82fe-42f1952786a4', version='HTTP/1.1', remote_ip='172.16.1.13')
Oct  4 09:16:38 devel rootthebox.py[1350]:     Traceback (most recent call last):
Oct  4 09:16:38 devel rootthebox.py[1350]:       File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1701, in _execute
Oct  4 09:16:38 devel rootthebox.py[1350]:         result = method(self.path_args, *self.path_kwargs)
Oct  4 09:16:38 devel rootthebox.py[1350]:       File "/var/ctf/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
Oct  4 09:16:38 devel rootthebox.py[1350]:         return method(self, args, *kwargs)
Oct  4 09:16:38 devel rootthebox.py[1350]:       File "/var/ctf/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
Oct  4 09:16:38 devel rootthebox.py[1350]:         return method(self, args, *kwargs)
Oct  4 09:16:38 devel rootthebox.py[1350]:       File "/var/ctf/RootTheBox/handlers/MissionsHandler.py", line 140, in post
Oct  4 09:16:38 devel rootthebox.py[1350]:         uuid and Flag.by_uuid(uuid).box.locked
Oct  4 09:16:38 devel rootthebox.py[1350]:     AttributeError: 'NoneType' object has no attribute 'box'
Oct  4 09:16:38 devel rootthebox.py[1350]: [E 201004 09:16:38 BaseHandlers:194] Request from 172.16.1.13 resulted in an error code 500:
Oct  4 09:16:38 devel rootthebox.py[1350]:     Traceback (most recent call last):
Oct  4 09:16:38 devel rootthebox.py[1350]:       File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1701, in _execute
Oct  4 09:16:38 devel rootthebox.py[1350]:         result = method(self.path_args, *self.path_kwargs)
Oct  4 09:16:38 devel rootthebox.py[1350]:       File "/var/ctf/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
Oct  4 09:16:38 devel rootthebox.py[1350]:         return method(self, args, *kwargs)
Oct  4 09:16:38 devel rootthebox.py[1350]:       File "/var/ctf/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
Oct  4 09:16:38 devel rootthebox.py[1350]:         return method(self, args, *kwargs)
Oct  4 09:16:38 devel rootthebox.py[1350]:       File "/var/ctf/RootTheBox/handlers/MissionsHandler.py", line 140, in post
Oct  4 09:16:38 devel rootthebox.py[1350]:         uuid and Flag.by_uuid(uuid).box.locked
Oct  4 09:16:38 devel rootthebox.py[1350]:     AttributeError: 'NoneType' object has no attribute 'box'
Oct  4 09:16:38 devel rootthebox.py[1350]:     
Oct  4 09:16:38 devel rootthebox.py[1350]: [E 201004 09:16:38 web:2246] 500 POST /user/missions/boxes?uuid=c0df1486-d535-4ba4-82fe-42f1952786a4 (172.16.1.13) 37.08ms
```

**Comment by jeffg2k** [comment]
Thanks for the report - fix pushed

**Comment by rstocks** [comment]
Hate to be that guy - but pulling this update has broken the app. The modified line in MissionsHandler.py appears to have an error:

```
root@rtb:/var/ctf/RootTheBox# ./rootthebox.py --start
[E 201006 00:50:29 rootthebox:54] Error: invalid syntax (MissionsHandler.py, line 141)
root@rtb:/var/ctf/RootTheBox# 
```
