### ISSUE TITLE
Mission Handler error

### ISSUE THREAD

**Issue by Robinx0** [moloch--/RootTheBox#453]
**Frontend** : 404 page.
**Backend log :**
``    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/rootthebox/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
        return method(self, *args, **kwargs)
      File "/home/rootthebox/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
        return method(self, *args, **kwargs)
      File "/home/rootthebox/RootTheBox/handlers/MissionsHandler.py", line 196, in post
        success = self.success_capture(flag, old_reward)
      File "/home/rootthebox/RootTheBox/handlers/MissionsHandler.py", line 347, in success_capture
        send_level_complete_webhook(user, box)
      File "/home/rootthebox/RootTheBox/libs/WebhookHelpers.py", line 66, in send_level_complete_webhook
        "reward": level.reward,
    AttributeError: 'Box' object has no attribute 'reward'
[E 210828 11:45:37 BaseHandlers:195] Request from [ip] resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/rootthebox/RootTheBox/libs/SecurityDecorators.py", line 46, in wrapper
        return method(self, *args, **kwargs)
      File "/home/rootthebox/RootTheBox/libs/SecurityDecorators.py", line 77, in wrapper
        return method(self, *args, **kwargs)
      File "/home/rootthebox/RootTheBox/handlers/MissionsHandler.py", line 196, in post
            "action": "capture_failed",
        success = self.success_capture(flag, old_reward)
      File "/home/rootthebox/RootTheBox/handlers/MissionsHandler.py", line 347, in success_capture
        send_level_complete_webhook(user, box)
      File "/home/rootthebox/RootTheBox/libs/WebhookHelpers.py", line 66, in send_level_complete_webhook
        "reward": level.reward,
    AttributeError: 'Box' object has no attribute 'reward'`

I get this error whenever I submit the last flag of total flags.

After some debugging, I thought changing the parameter of `send_level_complete_webhook(user, box)` in MissionHandlers.py to `send_level_complete_webhook(user, level)` because in this python file in the Boxhandler class we see `  level = GameLevel.by_id(box.game_level_id)` and GameLevel contains all the necessary attribute.

So, it looks like it fixes the whole issue.

[I don't know if it has been reported before, I noticed it so I created the issue Hopefully admin will fix that in the code. If it raises any other problem please reply.]

**Comment by jeffg2k** [comment]
Thanks for the report - patched in master and the 3.10.0 branch.

**Comment by Robinx0** [comment]
You are welcome.
