### ISSUE TITLE
Trouble using the botnet

### ISSUE THREAD

**Issue by estuart** [moloch--/RootTheBox#46]
When I try to connect a botnet I get the following error:

[ERROR] 2014-08-18 15:54:36,719 - Uncaught exception in /botnet/connect
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 369, in _run_callback
    callback(_args, *_kwargs)
  File "/home/rtb/Desktop/RootTheBox/handlers/BotnetHandlers.py", line 87, in open
    box = Box.by_ip_address(self.request.remote_ip)
AttributeError: 'module' object has no attribute 'by_ip_address'
[DEBUG] 2014-08-18 15:54:36,721 - Closing connection to bot at 10.0.2.6

Any idea what exactly could be causing this? I've tried to dig through the code and figure it out but have had no luck.

**Comment by jeffg2k** [comment]
Since there has been no activity on this issue, I'm going to assume moloch's fix addressed the issue and close this.  Reopen if needed.
