### ISSUE TITLE
3.12.0 registration is not working.

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#524]
While doing registration in rtb. I am getting following error.

You can merge with #522 

```
[E 221020 15:58:59 BaseHandlers:195] Request from 127.0.0.1 resulted in an error code 500:
    Traceback (most recent call last):
      File "<Python Path>lib\site-packages\tornado\web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "<Python Path>\PublicHandlers.py", line 371, in post
        user = self.create_user()
      File "<Python Path>\PublicHandlers.py", line 468, in create_user
        team = self.get_team()
      File "<Python Path>\PublicHandlers.py", line 520, in get_team
        return self.create_team()
      File "<Python Path>\PublicHandlers.py", line 538, in create_team
        team.purchased_source_code = []
      File "<Python Path>lib\site-packages\sqlalchemy\orm\attributes.py", line 459, in __set__
        self.impl.set(
      File "<Python Path>lib\site-packages\sqlalchemy\orm\attributes.py", line 1587, in set
        old = self.get(state, dict_, passive=PASSIVE_ONLY_PERSISTENT)
      File "<Python Path>lib\site-packages\sqlalchemy\orm\attributes.py", line 941, in get
        value = self._fire_loader_callables(state, key, passive)
      File "<Python Path>lib\site-packages\sqlalchemy\orm\attributes.py", line 977, in _fire_loader_callables
        return self.callable_(state, passive)
      File "<Python Path>lib\site-packages\sqlalchemy\orm\strategies.py", line 911, in _load_for_state
        return self._emit_lazyload(
      File "<Python Path>lib\site-packages\sqlalchemy\orm\strategies.py", line 1047, in _emit_lazyload
        result = session.execute(
      File "<Python Path>lib\site-packages\sqlalchemy\orm\session.py", line 1660, in execute
        ) = compile_state_cls.orm_pre_session_exec(
      File "<Python Path>lib\site-packages\sqlalchemy\orm\context.py", line 319, in orm_pre_session_exec
        session._autoflush()
      File "<Python Path>lib\site-packages\sqlalchemy\orm\session.py", line 2246, in _autoflush
        self.flush()
      File "<Python Path>lib\site-packages\sqlalchemy\orm\session.py", line 3383, in flush
        self._flush(objects)
      File "<Python Path>lib\site-packages\sqlalchemy\orm\session.py", line 3523, in _flush
        transaction.rollback(_capture_exception=True)
      File "<Python Path>lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
        compat.raise_(
      File "<Python Path>lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
        raise exception
      File "<Python Path>lib\site-packages\sqlalchemy\orm\session.py", line 3483, in _flush
        flush_context.execute()
      File "<Python Path>lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
        rec.execute(self)
      File "<Python Path>lib\site-packages\sqlalchemy\orm\unitofwork.py", line 579, in execute
        self.dependency_processor.process_saves(uow, states)
      File "<Python Path>lib\site-packages\sqlalchemy\orm\dependency.py", line 1182, in process_saves
        self._run_crud(
      File "<Python Path>lib\site-packages\sqlalchemy\orm\dependency.py", line 1207, in _run_crud
        raise exc.StaleDataError(
    sqlalchemy.orm.exc.StaleDataError: DELETE statement on table 'team_to_game_level' expected to delete 5 row(s); Only 10 were matched
```

**Comment by PunitTailor55** [comment]
It is working fine after added CRLF.
header.add("\r\n");
