### ISSUE TITLE
(bug?) Email Validation Error

### ISSUE THREAD

**Issue by PJNorrisS1** [moloch--/RootTheBox#569]
We have set up a server now to do email validation. Email is received but the token provided does not validate.
![image](https://github.com/moloch--/RootTheBox/assets/106666319/65869399-8d73-4720-b293-3a70fcba38e1)
Checked the logs - all looks as it should.
Dropped the DB and opened in sqlite and noted the registration_token table is empty - looks like the token is being generated, but it is not written to the DB ?

**Comment by eljeffeg** [comment]
registration_token is not the email_token.  registration_token is used for registering uses by sending them a code.  The email_token table should hold the email tokens.

**Comment by PJNorrisS1** [comment]
UPDATE: I cleared down that table of entries in email_token, tried registration again and it was successful. 
![image](https://github.com/moloch--/RootTheBox/assets/106666319/a4cb8791-5ab6-4126-a3ae-3fc27696b5f8)
Please can you fix clearing the token out? Thanks

**Comment by PJNorrisS1** [comment]
Ok, correction on the above, I hadn't pulled the latest release. However, I still am getting a glitch in the matrix...

Steps to recreate:
1. Login as admin, reset the game with players. Check DB - email_token table empty. 👍 
2. Logged out. registered a new user. received email validation.
3. Checked DB - one entry in there:
```
1|2023-06-12 13:59:29.374953|18|e3f877d57a70b0502a7aaaf220886a57a1102e8dc396c7ada9561ef26d3a6c17|0
```
4.  Clicked on link in email and get 404 error:
<img width="749" alt="image" src="https://github.com/moloch--/RootTheBox/assets/106666319/4adb275a-dd62-4b6e-aa37-1aa94be87222">

**Comment by PJNorrisS1** [comment]
Further to the above, I have repeated all the steps again and noticed, after registering, it completely borks the user management. Even without trying to validate, the user management in admin is 404 error.

**Comment by PJNorrisS1** [comment]
```
uk-webapp-1     | [E 230612 15:37:30 web:1871] Uncaught exception GET /admin/users (86.xxxxxx)
uk-webapp-1     |     HTTPServerRequest(protocol='https', host='uk.emea-threatops.com', method='GET', uri='/admin/users', version='HTTP/1.1', remote_ip='86.10.128.58')
uk-webapp-1     |     Traceback (most recent call last):
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1784, in _execute
uk-webapp-1     |         result = method(*self.path_args, **self.path_kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 91, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 46, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 130, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/handlers/AdminHandlers/AdminUserHandlers.py", line 53, in get
uk-webapp-1     |         self.render("admin/view/users.html", errors=None)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 940, in render
uk-webapp-1     |         html = self.render_string(template_name, **kwargs)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1089, in render_string
uk-webapp-1     |         return t.generate(**namespace)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/template.py", line 362, in generate
uk-webapp-1     |         return execute()
uk-webapp-1     |       File "admin/view/users_html.generated.py", line 1267, in _tt_execute
uk-webapp-1     |         _tt_tmp = user.is_email_valid()  # admin/view/users.html:520 (via main.html:32)
uk-webapp-1     |       File "/opt/rtb/models/User.py", line 384, in is_email_valid
uk-webapp-1     |         emailtoken = EmailToken.by_user_id(self.id)
uk-webapp-1     |       File "/opt/rtb/models/EmailToken.py", line 53, in by_user_id
uk-webapp-1     |         return dbsession.query(cls).filter_by(user_id=user_id).last()
uk-webapp-1     |     AttributeError: 'Query' object has no attribute 'last'
uk-webapp-1     | [E 230612 15:37:30 BaseHandlers:196] Request from 86.xxxxx resulted in an error code 500:
uk-webapp-1     |     Traceback (most recent call last):
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1784, in _execute
uk-webapp-1     |         result = method(*self.path_args, **self.path_kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 91, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 46, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 130, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/handlers/AdminHandlers/AdminUserHandlers.py", line 53, in get
uk-webapp-1     |         self.render("admin/view/users.html", errors=None)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 940, in render
uk-webapp-1     |         html = self.render_string(template_name, **kwargs)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1089, in render_string
uk-webapp-1     |         return t.generate(**namespace)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/template.py", line 362, in generate
uk-webapp-1     |         return execute()
uk-webapp-1     |       File "admin/view/users_html.generated.py", line 1267, in _tt_execute
uk-webapp-1     |         _tt_tmp = user.is_email_valid()  # admin/view/users.html:520 (via main.html:32)
uk-webapp-1     |       File "/opt/rtb/models/User.py", line 384, in is_email_valid
uk-webapp-1     |         emailtoken = EmailToken.by_user_id(self.id)
uk-webapp-1     |       File "/opt/rtb/models/EmailToken.py", line 53, in by_user_id
uk-webapp-1     |         return dbsession.query(cls).filter_by(user_id=user_id).last()
uk-webapp-1     |     AttributeError: 'Query' object has no attribute 'last'
uk-webapp-1     |     
uk-webapp-1     | [E 230612 15:37:30 web:2344] 500 GET /admin/users (86.10.128.58) 66.79ms
uk-webapp-1     | [I 230612 15:37:30 web:2344] 101 GET /connect/notifications/updates (86.10.128.58) 0.74ms
```

**Comment by PJNorrisS1** [comment]
Sorry - pulled the latest which updated the EmailToken.py file. Compiled and built. 
Logged in, reset the game so nothing exists. Checked I could access users. no problems.
Registered, email received, click the link and get 404 error still. 

```
uk-webapp-1     | [E 230612 16:13:19 web:1871] Uncaught exception GET /admin/users (86.xxxx)
uk-webapp-1     |     HTTPServerRequest(protocol='https', host='uk.emea-threatops.com', method='GET', uri='/admin/users', version='HTTP/1.1', remote_ip='86.10.128.58')
uk-webapp-1     |     Traceback (most recent call last):
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1784, in _execute
uk-webapp-1     |         result = method(*self.path_args, **self.path_kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 91, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 46, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 130, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/handlers/AdminHandlers/AdminUserHandlers.py", line 53, in get
uk-webapp-1     |         self.render("admin/view/users.html", errors=None)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 940, in render
uk-webapp-1     |         html = self.render_string(template_name, **kwargs)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1089, in render_string
uk-webapp-1     |         return t.generate(**namespace)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/template.py", line 362, in generate
uk-webapp-1     |         return execute()
uk-webapp-1     |       File "admin/view/users_html.generated.py", line 1267, in _tt_execute
uk-webapp-1     |         _tt_tmp = user.is_email_valid()  # admin/view/users.html:520 (via main.html:32)
uk-webapp-1     |       File "/opt/rtb/models/User.py", line 384, in is_email_valid
uk-webapp-1     |         emailtoken = EmailToken.by_user_id(self.id)
uk-webapp-1     |       File "/opt/rtb/models/EmailToken.py", line 53, in by_user_id
uk-webapp-1     |         return dbsession.query(cls).filter_by(user_id=user_id).order_by(id.desc()).first()
uk-webapp-1     |     AttributeError: 'builtin_function_or_method' object has no attribute 'desc'
uk-webapp-1     | [E 230612 16:13:19 BaseHandlers:196] Request from 86.xxxx resulted in an error code 500:
uk-webapp-1     |     Traceback (most recent call last):
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1784, in _execute
uk-webapp-1     |         result = method(*self.path_args, **self.path_kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 91, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 46, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/libs/SecurityDecorators.py", line 130, in wrapper
uk-webapp-1     |         return method(self, *args, **kwargs)
uk-webapp-1     |       File "/opt/rtb/handlers/AdminHandlers/AdminUserHandlers.py", line 53, in get
uk-webapp-1     |         self.render("admin/view/users.html", errors=None)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 940, in render
uk-webapp-1     |         html = self.render_string(template_name, **kwargs)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1089, in render_string
uk-webapp-1     |         return t.generate(**namespace)
uk-webapp-1     |       File "/usr/local/lib/python3.8/site-packages/tornado/template.py", line 362, in generate
uk-webapp-1     |         return execute()
uk-webapp-1     |       File "admin/view/users_html.generated.py", line 1267, in _tt_execute
uk-webapp-1     |         _tt_tmp = user.is_email_valid()  # admin/view/users.html:520 (via main.html:32)
uk-webapp-1     |       File "/opt/rtb/models/User.py", line 384, in is_email_valid
uk-webapp-1     |         emailtoken = EmailToken.by_user_id(self.id)
uk-webapp-1     |       File "/opt/rtb/models/EmailToken.py", line 53, in by_user_id
uk-webapp-1     |         return dbsession.query(cls).filter_by(user_id=user_id).order_by(id.desc()).first()
uk-webapp-1     |     AttributeError: 'builtin_function_or_method' object has no attribute 'desc'
```

**Comment by eljeffeg** [comment]
Dang.. stack exchange fail.  Ok, pushed a new one. lol

**Comment by eljeffeg** [comment]
Sorry, this is getting embarrassing. lol. I don't have email setup to test it.  Pushed an update.

**Comment by PJNorrisS1** [comment]
Thanks. Will test in next hour. No problem! Really appreciate you jumping on this. On 12 Jun 2023, at 19:28, ElJeffe ***@***.***> wrote:﻿
Sorry, this is getting embarrassing. lol. I don't have email setup to test it.  Pushed an update.

**Comment by PJNorrisS1** [comment]
Hi, tested and appears to all be working as it should. One observation, if I register a user, then verify it. If I delete the user from admin, the entry in email_token is still there. Creating a new user generates another entry in there with same user id (18 in this case). Although it verified okay, is this normal behaviour? Should you be clearing the entry in email_token when deleting a user, as well as when you do a master reset?
```
1|2023-06-12 20:30:59.154456|18|220ffe8008dfd6f49e5bd4117fed673825603a33a3bf13f99e94f04af0cf12b2|1
2|2023-06-12 20:32:45.517535|18|b19c9f635671e953916799e6d94aba736c3082379a7e7a1bd56b1da3e8a05ea8|1
```

**Comment by PJNorrisS1** [comment]
Further testing - seem's okay... i created a user, but not validated it (bit is 0); I then deleted the user, created a new user and validated and it worked.
```
1|2023-06-12 20:30:59.154456|18|220ffe8008dfd6f49e5bd4117fed673825603a33a3bf13f99e94f04af0cf12b2|1
2|2023-06-12 20:32:45.517535|18|b19c9f635671e953916799e6d94aba736c3082379a7e7a1bd56b1da3e8a05ea8|1
3|2023-06-12 20:36:16.242515|18|e57acdc3c11a39109f69b2c004529ecf413002a8c5f7667a145e39b505c7a001|0
4|2023-06-12 20:37:06.083818|18|2cc9a765e30c8ffe219fcfabde3ab2f39384af51d5ae848badafae562eed74b4|0
sqlite> select * from email_token;
1|2023-06-12 20:30:59.154456|18|220ffe8008dfd6f49e5bd4117fed673825603a33a3bf13f99e94f04af0cf12b2|1
2|2023-06-12 20:32:45.517535|18|b19c9f635671e953916799e6d94aba736c3082379a7e7a1bd56b1da3e8a05ea8|1
3|2023-06-12 20:36:16.242515|18|e57acdc3c11a39109f69b2c004529ecf413002a8c5f7667a145e39b505c7a001|0
4|2023-06-12 20:37:06.083818|18|2cc9a765e30c8ffe219fcfabde3ab2f39384af51d5ae848badafae562eed74b4|1
```
but could see this might be a future problem if the user is not cleared out? Is this what got us in to trouble before?

**Comment by eljeffeg** [comment]
Yes, that makes sense.  Unlike other tables, we didn't link the EmailTokens to the User as a foreign key, which is why we had to delete them separately.

**Comment by eljeffeg** [comment]
Pushed an update to hopefully resolve that.

**Comment by PJNorrisS1** [comment]
Tested... didn't erase the entry. 
1. reset whole game.
2. registered a user
3. select * from email_token; shows the one entry 👍 
4. logged in as admin
5. deleted the unvalidated user
6. checked the db and the entry still there.
```
uk-webapp-1     | [I 230612 21:20:26 PublicHandlers:679] Email Validation sent for paul@pjnorris.com
uk-webapp-1     | [I 230612 21:20:26 web:2344] 200 POST /registration (86.10.128.58) 857.85ms
uk-webapp-1     | [I 230612 21:20:26 web:2344] 101 GET /connect/notifications/updates (86.10.128.58) 0.60ms
uk-webapp-1     | [I 230612 21:20:32 web:2344] 200 GET /login (86.10.128.58) 0.95ms
uk-webapp-1     | [I 230612 21:20:32 web:2344] 101 GET /connect/notifications/updates (86.10.128.58) 0.98ms
uk-webapp-1     | [I 230612 21:20:34 PublicHandlers:317] Successful login: admin from 86.10.128.58
uk-webapp-1     | [I 230612 21:20:34 web:2344] 302 POST /login (86.10.128.58) 163.62ms
uk-webapp-1     | [I 230612 21:20:34 web:2344] 200 GET /user (86.10.128.58) 177.63ms
uk-webapp-1     | [I 230612 21:20:35 web:2344] 304 GET /scoreboard/ajax/timer (86.10.128.58) 0.70ms
uk-webapp-1     | [I 230612 21:20:35 web:2344] 101 GET /connect/notifications/updates (86.10.128.58) 0.66ms
uk-webapp-1     | [I 230612 21:20:37 web:2344] 200 GET /admin/users (86.10.128.58) 43.67ms
uk-webapp-1     | [I 230612 21:20:37 web:2344] 101 GET /connect/notifications/updates (86.10.128.58) 0.69ms
uk-webapp-1     | [I 230612 21:20:41 AdminUserHandlers:273] Deleted Team: 'PJN1'
uk-webapp-1     | [I 230612 21:20:41 web:2344] 302 POST /admin/users/delete/team (86.10.128.58) 36.32ms
uk-webapp-1     | [I 230612 21:20:41 web:2344] 200 GET /admin/users (86.10.128.58) 11.33ms
uk-webapp-1     | [I 230612 21:20:41 web:2344] 101 GET /connect/notifications/updates (86.10.128.58) 0.57ms
uk-webapp-1     | [I 230612 21:20:54 web:2344] 200 GET / (86.10.128.58) 0.93ms
```

**Comment by eljeffeg** [comment]
Yup, was not returning an array.  Getting closer.

**Comment by eljeffeg** [comment]
I think that might have been due to a team delete instead of a user delete.  I've now added it to both.

**Comment by PJNorrisS1** [comment]
On the above point, we ran a workshop today with email registrations enabled. All went okay, execpt we had a couple of players whose email system filtered their emails. We managed to get them released, but took time. It would be nice for the Admin to 'validate' a user as my comment above, in the case an email doesn't get pushed through.

**Comment by PunitTailor55** [comment]
In addition to that we need to make admin users pagination as well.

**Comment by eljeffeg** [comment]
Pushed a change so that unlock will also validate email.

**Comment by PJNorrisS1** [comment]
Perfect! Tried and tested. Thank you
