### ISSUE TITLE
Login failing, no attribute or memcached not found on Ubuntu 22.0

### ISSUE THREAD

**Issue by submac100** [moloch--/RootTheBox#594]
Hi Moloch,

I know you have stated earlier that only upto python 3.8 is supported. I have tested this on the latest python 3.10 and with a virtual environment using python 3.8 but receive the same results. Could you offer some assistance on why I am receiving this error when logging in?

 uname -v
#34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2

Request from 127.0.0.1 resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/rich/gitstuff/RootTheBox/libs/SecurityDecorators.py", line 127, in wrapper
        return method(self, *args, **kwargs)
      File "/home/rich/gitstuff/RootTheBox/handlers/PublicHandlers.py", line 239, in post
        self.valid_login(user)
      File "/home/rich/gitstuff/RootTheBox/handlers/PublicHandlers.py", line 310, in valid_login
        self.successful_login(user)
      File "/home/rich/gitstuff/RootTheBox/handlers/PublicHandlers.py", line 325, in successful_login
        self.start_session()
      File "/home/rich/gitstuff/RootTheBox/handlers/BaseHandlers.py", line 99, in start_session
        self.session = self._create_session()
      File "/home/rich/gitstuff/RootTheBox/handlers/BaseHandlers.py", line 144, in _create_session
        kwargs = {"connection": self.memcached, "ip_address": self.request.remote_ip}
      File "/home/rich/gitstuff/RootTheBox/handlers/BaseHandlers.py", line 139, in memcached
        self._memcached = MemcachedConnect()
      File "/home/rich/gitstuff/RootTheBox/libs/Sessions.py", line 241, in MemcachedConnect
        client = memcache.Client(servers, username=user, password=passw)
    AttributeError: module 'memcache' has no attribute 'Client'

**Comment by eljeffeg** [comment]
Looks like `python-binary-memcached` is not installed.
Sessions.py uses this.. 
`import bmemcached as memcache`

**Comment by submac100** [comment]
wow, thanks so much for the fast response, that was problem

**Comment by submac100** [comment]
resolved with pip install python-binary-memcached
