### ISSUE TITLE
Cant export game configuration

### ISSUE THREAD

**Issue by ktravnik** [moloch--/RootTheBox#606]
Hello I am getting "404 - Glitch in the Matrix

It looks like you typed a URL incorrectly, or were attempting to find something you ought not have access to.
The only other possibility is that I messed up some of the code, and that doesn't seem very likely." if I want to do export of game configuration, also I am not able to register new users due to error "Invalid bank password lenght" 

Ive used docker.

Anyone having same trouble ?

Thanks,
Chris.

**Comment by eljeffeg** [comment]
We may need more information to reproduce this for troubleshooting.  Could you explain your setup a bit more?

**Comment by dansibleadm** [comment]
I dont have the same problem but similar. If in some place I have characters and words on latin - exception is raised when im trying to export:

   Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/rtb/libs/SecurityDecorators.py", line 113, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/rtb/libs/SecurityDecorators.py", line 68, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/rtb/libs/SecurityDecorators.py", line 152, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/rtb/handlers/AdminHandlers/AdminGameHandlers.py", line 553, in post
        self.write_xml(xml_dom.toprettyxml())
      File "/opt/rtb/handlers/AdminHandlers/AdminGameHandlers.py", line 565, in write_xml
        self.finish()
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1238, in finish
        future = self.flush(include_footers=True)
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1175, in flush
        return self.request.connection.write_headers(
      File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 450, in write_headers
        lines.extend(line.encode("latin1") for line in header_lines)
      File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 450, in <genexpr>
        lines.extend(line.encode("latin1") for line in header_lines)
    UnicodeEncodeError: 'latin-1' codec can't encode characters in position 42-52: ordinal not in range(256)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1285, in send_error
        self.finish()
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1239, in finish
        self.request.connection.finish()
      File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 510, in finish
        raise httputil.HTTPOutputError(
    tornado.httputil.HTTPOutputError: Tried to write 887928 bytes less than Content-Length

**Comment by eljeffeg** [comment]
It looks like this is utf-8 encoded, so I'm going to close this thinking it's been resolved.  Let me know if it is still and issue.

```py
self.set_header("Content-Length", len(encode(xml_doc, "utf-8")))
self.write(encode(xml_doc, "utf-8"))
self.finish()
```
