### ISSUE TITLE
Python 3.12 not supported

### ISSUE THREAD

**Issue by mspreitz** [moloch--/RootTheBox#621]
when starting RootTheBox directly out of a venv (without docker) it runs into an issue because the `nose` dependency seems not to be ready for Python 3.12

```
(rootthebox) ubuntu@ctf:~/RootTheBox$ python3 rootthebox.py
Traceback (most recent call last):
  File "/home/ubuntu/RootTheBox/rootthebox.py", line 33, in <module>
    import nose
  File "/home/ubuntu/RootTheBox/rootthebox/lib/python3.12/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/home/ubuntu/RootTheBox/rootthebox/lib/python3.12/site-packages/nose/core.py", line 12, in <module>
    from nose.loader import defaultTestLoader
  File "/home/ubuntu/RootTheBox/rootthebox/lib/python3.12/site-packages/nose/loader.py", line 21, in <module>
    from nose.importer import Importer, add_path, remove_path
  File "/home/ubuntu/RootTheBox/rootthebox/lib/python3.12/site-packages/nose/importer.py", line 12, in <module>
    from imp import find_module, load_module, acquire_lock, release_lock
ModuleNotFoundError: No module named 'imp'
```

**Comment by mspreitz** [comment]
my current fix to get it still running is by just deleting the `import nose` line within the `rootthebox.py` - but I'm sure that this is not the best option

**Comment by howlingunit** [comment]
Another work around I've found for this is replacing the `nose` requirement with `nose-py3`
this works but I haven't tested it too much

**Comment by eljeffeg** [comment]
I created a new branch based on `python:3.13-slim-bookworm` if you want to test it.
https://github.com/moloch--/RootTheBox/tree/3.15.x
