### ISSUE TITLE
Scoreboard Summary

### ISSUE THREAD

**Issue by AnarKyx01** [moloch--/RootTheBox#92]
When checking scoreboard summary.

[E 150520 22:38:31 web:1421] Uncaught exception GET /scoreboard/ajax/summary (192.168.1.41)
    HTTPServerRequest(protocol='http', host='192.168.1.205:8888', method='GET', uri='/scoreboard/ajax/summary', version='HTTP/1.1', remote_ip='192.168.1.41', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '192.168.1.205:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.1.205:8888/scoreboard'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/anarky/PycharmProjects/RootTheBox/handlers/ScoreboardHandlers.py", line 83, in get
        uri[args[0]]()
      File "/home/anarky/PycharmProjects/RootTheBox/handlers/ScoreboardHandlers.py", line 89, in summary_table
        self.render('scoreboard/summary_table.html', teams=Team.ranks())
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 664, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 771, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 278, in generate
        return execute()
      File "scoreboard/summary_table_html.generated.py", line 51, in _tt_execute
        _tt_tmp = team.levels[-1].number  # scoreboard/summary_table.html:18
    IndexError: list index out of range
[E 150520 22:38:31 web:1825] 500 GET /scoreboard/ajax/summary (192.168.1.41) 22.10ms
2015-05-20 22:38:31,734 INFO sqlalchemy.engine.base.Engine ROLLBACK
[I 150520 22:38:31 base:666] ROLLBACK

**Comment by AnarKyx01** [comment]
Suspect same as #53
