### ISSUE TITLE
Error thrown when trying to run a bot(win)

### ISSUE THREAD

**Issue by AnarKyx01** [moloch--/RootTheBox#94]
[E 150522 20:34:57 websocket:405] Uncaught exception in /botnet/connect
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 402, in _run_callback
callback(args, *kwargs)
File "/home/anarky/PycharmProjects/RootTheBox/handlers/BotnetHandlers.py", line 87, in open
box = Box.by_ip_address(self.request.remote_ip)
File "/home/anarky/PycharmProjects/RootTheBox/models/Box.py", line 123, in by_ip_address
ip = dbsession.query(IpAddress).by_address(ip_addr).first()
AttributeError: 'Query' object has no attribute 'by_address'

**Comment by AnarKyx01** [comment]
last pull fixed this issue(windows executable need recompile still). Also a duplicate of issue #46
