### ISSUE TITLE
Error when attempting to connect a 2nd bot or view scoreboard w/ bots

### ISSUE THREAD

**Issue by AnarKyx01** [moloch--/RootTheBox#96]
It appears the botnet dict is maybe not created correctly? the uuid exists in the sql table, but when printing out the dict, I'm getting 1 uuid(didn't pay attention to what the uuid corresponded too) and a handful of memory locations.

[E 150601 05:19:30 websocket:405] Uncaught exception in /botnet/connect
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 402, in _run_callback
        callback(*args, **kwargs)
      File "/home/anarky/PycharmProjects/RootTheBox/handlers/BotnetHandlers.py", line 109, in on_message
        self.opcodes[req['opcode']](req)
      File "/home/anarky/PycharmProjects/RootTheBox/handlers/BotnetHandlers.py", line 139, in interrogation_response
        self.add_to_botnet()
      File "/home/anarky/PycharmProjects/RootTheBox/handlers/BotnetHandlers.py", line 145, in add_to_botnet
        count = self.bot_manager.count_by_team(self.team_name)
      File "/home/anarky/PycharmProjects/RootTheBox/libs/BotManager.py", line 133, in count_by_team
        return len(self.by_team(team))
      File "/home/anarky/PycharmProjects/RootTheBox/libs/BotManager.py", line 130, in by_team
        return [self.botnet[bot.wsock_uuid] for bot in bots]
    KeyError: u'b673ef67-986a-4134-8cba-891ad23ede7a'
2015-06-01 05:19:30,286 INFO sqlalchemy.engine.base.Engine SELECT bot.id AS bot_id, bot.created AS bot_created, bot.last_ping AS bot_last_ping, bot.wsock_uuid AS bot_wsock_uuid, bot.team_uuid AS bot_team_uuid, bot.box_uuid AS bot_box_uuid, bot.remote_ip AS bot_remote_ip, bot.total_reward AS bot_total_reward, bot.team_name AS bot_team_name, bot.box_name AS bot_box_name 
FROM bot 
WHERE bot.wsock_uuid = ?
 LIMIT ? OFFSET ?

**Comment by AnarKyx01** [comment]
Update

Everything works fine until you stop rootthebox.  Once it starts it back up, it does not appear to read the local database and get all the bots previously submitted. However if you try to resubmit the bot, it's already in the database, thus cannot be resubmitted. Not sure if this is intended or not (Little bot documentation around). At this point, you need to dump the bot database to get it working.(Should this be happening at start or should it read the database?)

**Comment by moloch--** [comment]
Hurm, seems like we could go either way. I think the simplest thing to do would be to flush the database when the game is stopped.
